// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: descriptor.proto

package com.google.protobuf;

/**
 * Protobuf type {@code google.protobuf.FileOptions}
 */
public  final class FileOptions extends
    com.google.protobuf.GeneratedMessage.ExtendableMessage<
      FileOptions> implements FileOptionsOrBuilder {
  // Use FileOptions.newBuilder() to construct.
  private FileOptions(com.google.protobuf.GeneratedMessage.ExtendableBuilder<com.google.protobuf.FileOptions, ?> builder) {
    super(builder);
    this.unknownFields = builder.getUnknownFields();
  }
  private FileOptions(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

  private static final FileOptions defaultInstance;
  public static FileOptions getDefaultInstance() {
    return defaultInstance;
  }

  public FileOptions getDefaultInstanceForType() {
    return defaultInstance;
  }

  private final com.google.protobuf.UnknownFieldSet unknownFields;
  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
    return this.unknownFields;
  }
  private FileOptions(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    initFields();
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownField(input, unknownFields,
                                   extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            bitField0_ |= 0x00000001;
            javaPackage_ = input.readBytes();
            break;
          }
          case 66: {
            bitField0_ |= 0x00000002;
            javaOuterClassname_ = input.readBytes();
            break;
          }
          case 72: {
            int rawValue = input.readEnum();
            com.google.protobuf.FileOptions.OptimizeMode value = com.google.protobuf.FileOptions.OptimizeMode.valueOf(rawValue);
            if (value == null) {
              unknownFields.mergeVarintField(9, rawValue);
            } else {
              bitField0_ |= 0x00000010;
              optimizeFor_ = value;
            }
            break;
          }
          case 80: {
            bitField0_ |= 0x00000004;
            javaMultipleFiles_ = input.readBool();
            break;
          }
          case 90: {
            bitField0_ |= 0x00000020;
            goPackage_ = input.readBytes();
            break;
          }
          case 128: {
            bitField0_ |= 0x00000040;
            ccGenericServices_ = input.readBool();
            break;
          }
          case 136: {
            bitField0_ |= 0x00000080;
            javaGenericServices_ = input.readBool();
            break;
          }
          case 144: {
            bitField0_ |= 0x00000100;
            pyGenericServices_ = input.readBool();
            break;
          }
          case 160: {
            bitField0_ |= 0x00000008;
            javaGenerateEqualsAndHash_ = input.readBool();
            break;
          }
          case 7994: {
            if (!((mutable_bitField0_ & 0x00000200) == 0x00000200)) {
              uninterpretedOption_ = new java.util.ArrayList<com.google.protobuf.UninterpretedOption>();
              mutable_bitField0_ |= 0x00000200;
            }
            uninterpretedOption_.add(input.readMessage(com.google.protobuf.UninterpretedOption.PARSER, extensionRegistry));
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e.getMessage()).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000200) == 0x00000200)) {
        uninterpretedOption_ = java.util.Collections.unmodifiableList(uninterpretedOption_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.google.protobuf.DescriptorProtos.internal_static_google_protobuf_FileOptions_descriptor;
  }

  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.google.protobuf.DescriptorProtos.internal_static_google_protobuf_FileOptions_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.google.protobuf.FileOptions.class, com.google.protobuf.FileOptions.Builder.class);
  }

  public static com.google.protobuf.Parser<FileOptions> PARSER =
      new com.google.protobuf.AbstractParser<FileOptions>() {
    public FileOptions parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new FileOptions(input, extensionRegistry);
    }
  };

  @java.lang.Override
  public com.google.protobuf.Parser<FileOptions> getParserForType() {
    return PARSER;
  }

  /**
   * Protobuf enum {@code google.protobuf.FileOptions.OptimizeMode}
   *
   * <pre>
   * Generated classes can be optimized for speed or code size.
   * </pre>
   */
  public enum OptimizeMode
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>SPEED = 1;</code>
     *
     * <pre>
     * Generate complete code for parsing, serialization,
     * </pre>
     */
    SPEED(0, 1),
    /**
     * <code>CODE_SIZE = 2;</code>
     *
     * <pre>
     * etc.
     * </pre>
     */
    CODE_SIZE(1, 2),
    /**
     * <code>LITE_RUNTIME = 3;</code>
     *
     * <pre>
     * Generate code using MessageLite and the lite runtime.
     * </pre>
     */
    LITE_RUNTIME(2, 3),
    ;

    /**
     * <code>SPEED = 1;</code>
     *
     * <pre>
     * Generate complete code for parsing, serialization,
     * </pre>
     */
    public static final int SPEED_VALUE = 1;
    /**
     * <code>CODE_SIZE = 2;</code>
     *
     * <pre>
     * etc.
     * </pre>
     */
    public static final int CODE_SIZE_VALUE = 2;
    /**
     * <code>LITE_RUNTIME = 3;</code>
     *
     * <pre>
     * Generate code using MessageLite and the lite runtime.
     * </pre>
     */
    public static final int LITE_RUNTIME_VALUE = 3;


    public final int getNumber() { return value; }

    public static OptimizeMode valueOf(int value) {
      switch (value) {
        case 1: return SPEED;
        case 2: return CODE_SIZE;
        case 3: return LITE_RUNTIME;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<OptimizeMode>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<OptimizeMode>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<OptimizeMode>() {
            public OptimizeMode findValueByNumber(int number) {
              return OptimizeMode.valueOf(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.google.protobuf.FileOptions.getDescriptor().getEnumTypes().get(0);
    }

    private static final OptimizeMode[] VALUES = values();

    public static OptimizeMode valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int index;
    private final int value;

    private OptimizeMode(int index, int value) {
      this.index = index;
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:google.protobuf.FileOptions.OptimizeMode)
  }

  private int bitField0_;
  // optional string java_package = 1;
  public static final int JAVA_PACKAGE_FIELD_NUMBER = 1;
  private java.lang.Object javaPackage_;
  /**
   * <code>optional string java_package = 1;</code>
   *
   * <pre>
   * Sets the Java package where classes generated from this .proto will be
   * placed.  By default, the proto package is used, but this is often
   * inappropriate because proto packages do not normally start with backwards
   * domain names.
   * </pre>
   */
  public boolean hasJavaPackage() {
    return ((bitField0_ & 0x00000001) == 0x00000001);
  }
  /**
   * <code>optional string java_package = 1;</code>
   *
   * <pre>
   * Sets the Java package where classes generated from this .proto will be
   * placed.  By default, the proto package is used, but this is often
   * inappropriate because proto packages do not normally start with backwards
   * domain names.
   * </pre>
   */
  public java.lang.String getJavaPackage() {
    java.lang.Object ref = javaPackage_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        javaPackage_ = s;
      }
      return s;
    }
  }
  /**
   * <code>optional string java_package = 1;</code>
   *
   * <pre>
   * Sets the Java package where classes generated from this .proto will be
   * placed.  By default, the proto package is used, but this is often
   * inappropriate because proto packages do not normally start with backwards
   * domain names.
   * </pre>
   */
  public com.google.protobuf.ByteString
      getJavaPackageBytes() {
    java.lang.Object ref = javaPackage_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      javaPackage_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  // optional string java_outer_classname = 8;
  public static final int JAVA_OUTER_CLASSNAME_FIELD_NUMBER = 8;
  private java.lang.Object javaOuterClassname_;
  /**
   * <code>optional string java_outer_classname = 8;</code>
   *
   * <pre>
   * If set, all the classes from the .proto file are wrapped in a single
   * outer class with the given name.  This applies to both Proto1
   * (equivalent to the old "--one_java_file" option) and Proto2 (where
   * a .proto always translates to a single class, but you may want to
   * explicitly choose the class name).
   * </pre>
   */
  public boolean hasJavaOuterClassname() {
    return ((bitField0_ & 0x00000002) == 0x00000002);
  }
  /**
   * <code>optional string java_outer_classname = 8;</code>
   *
   * <pre>
   * If set, all the classes from the .proto file are wrapped in a single
   * outer class with the given name.  This applies to both Proto1
   * (equivalent to the old "--one_java_file" option) and Proto2 (where
   * a .proto always translates to a single class, but you may want to
   * explicitly choose the class name).
   * </pre>
   */
  public java.lang.String getJavaOuterClassname() {
    java.lang.Object ref = javaOuterClassname_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        javaOuterClassname_ = s;
      }
      return s;
    }
  }
  /**
   * <code>optional string java_outer_classname = 8;</code>
   *
   * <pre>
   * If set, all the classes from the .proto file are wrapped in a single
   * outer class with the given name.  This applies to both Proto1
   * (equivalent to the old "--one_java_file" option) and Proto2 (where
   * a .proto always translates to a single class, but you may want to
   * explicitly choose the class name).
   * </pre>
   */
  public com.google.protobuf.ByteString
      getJavaOuterClassnameBytes() {
    java.lang.Object ref = javaOuterClassname_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      javaOuterClassname_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  // optional bool java_multiple_files = 10 [default = false];
  public static final int JAVA_MULTIPLE_FILES_FIELD_NUMBER = 10;
  private boolean javaMultipleFiles_;
  /**
   * <code>optional bool java_multiple_files = 10 [default = false];</code>
   *
   * <pre>
   * If set true, then the Java code generator will generate a separate .java
   * file for each top-level message, enum, and service defined in the .proto
   * file.  Thus, these types will *not* be nested inside the outer class
   * named by java_outer_classname.  However, the outer class will still be
   * generated to contain the file's getDescriptor() method as well as any
   * top-level extensions defined in the file.
   * </pre>
   */
  public boolean hasJavaMultipleFiles() {
    return ((bitField0_ & 0x00000004) == 0x00000004);
  }
  /**
   * <code>optional bool java_multiple_files = 10 [default = false];</code>
   *
   * <pre>
   * If set true, then the Java code generator will generate a separate .java
   * file for each top-level message, enum, and service defined in the .proto
   * file.  Thus, these types will *not* be nested inside the outer class
   * named by java_outer_classname.  However, the outer class will still be
   * generated to contain the file's getDescriptor() method as well as any
   * top-level extensions defined in the file.
   * </pre>
   */
  public boolean getJavaMultipleFiles() {
    return javaMultipleFiles_;
  }

  // optional bool java_generate_equals_and_hash = 20 [default = false];
  public static final int JAVA_GENERATE_EQUALS_AND_HASH_FIELD_NUMBER = 20;
  private boolean javaGenerateEqualsAndHash_;
  /**
   * <code>optional bool java_generate_equals_and_hash = 20 [default = false];</code>
   *
   * <pre>
   * If set true, then the Java code generator will generate equals() and
   * hashCode() methods for all messages defined in the .proto file. This is
   * purely a speed optimization, as the AbstractMessage base class includes
   * reflection-based implementations of these methods.
   * </pre>
   */
  public boolean hasJavaGenerateEqualsAndHash() {
    return ((bitField0_ & 0x00000008) == 0x00000008);
  }
  /**
   * <code>optional bool java_generate_equals_and_hash = 20 [default = false];</code>
   *
   * <pre>
   * If set true, then the Java code generator will generate equals() and
   * hashCode() methods for all messages defined in the .proto file. This is
   * purely a speed optimization, as the AbstractMessage base class includes
   * reflection-based implementations of these methods.
   * </pre>
   */
  public boolean getJavaGenerateEqualsAndHash() {
    return javaGenerateEqualsAndHash_;
  }

  // optional .google.protobuf.FileOptions.OptimizeMode optimize_for = 9 [default = SPEED];
  public static final int OPTIMIZE_FOR_FIELD_NUMBER = 9;
  private com.google.protobuf.FileOptions.OptimizeMode optimizeFor_;
  /**
   * <code>optional .google.protobuf.FileOptions.OptimizeMode optimize_for = 9 [default = SPEED];</code>
   */
  public boolean hasOptimizeFor() {
    return ((bitField0_ & 0x00000010) == 0x00000010);
  }
  /**
   * <code>optional .google.protobuf.FileOptions.OptimizeMode optimize_for = 9 [default = SPEED];</code>
   */
  public com.google.protobuf.FileOptions.OptimizeMode getOptimizeFor() {
    return optimizeFor_;
  }

  // optional string go_package = 11;
  public static final int GO_PACKAGE_FIELD_NUMBER = 11;
  private java.lang.Object goPackage_;
  /**
   * <code>optional string go_package = 11;</code>
   *
   * <pre>
   * Sets the Go package where structs generated from this .proto will be
   * placed.  There is no default.
   * </pre>
   */
  public boolean hasGoPackage() {
    return ((bitField0_ & 0x00000020) == 0x00000020);
  }
  /**
   * <code>optional string go_package = 11;</code>
   *
   * <pre>
   * Sets the Go package where structs generated from this .proto will be
   * placed.  There is no default.
   * </pre>
   */
  public java.lang.String getGoPackage() {
    java.lang.Object ref = goPackage_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        goPackage_ = s;
      }
      return s;
    }
  }
  /**
   * <code>optional string go_package = 11;</code>
   *
   * <pre>
   * Sets the Go package where structs generated from this .proto will be
   * placed.  There is no default.
   * </pre>
   */
  public com.google.protobuf.ByteString
      getGoPackageBytes() {
    java.lang.Object ref = goPackage_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      goPackage_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  // optional bool cc_generic_services = 16 [default = false];
  public static final int CC_GENERIC_SERVICES_FIELD_NUMBER = 16;
  private boolean ccGenericServices_;
  /**
   * <code>optional bool cc_generic_services = 16 [default = false];</code>
   *
   * <pre>
   * Should generic services be generated in each language?  "Generic" services
   * are not specific to any particular RPC system.  They are generated by the
   * main code generators in each language (without additional plugins).
   * Generic services were the only kind of service generation supported by
   * early versions of proto2.
   *
   * Generic services are now considered deprecated in favor of using plugins
   * that generate code specific to your particular RPC system.  Therefore,
   * these default to false.  Old code which depends on generic services should
   * explicitly set them to true.
   * </pre>
   */
  public boolean hasCcGenericServices() {
    return ((bitField0_ & 0x00000040) == 0x00000040);
  }
  /**
   * <code>optional bool cc_generic_services = 16 [default = false];</code>
   *
   * <pre>
   * Should generic services be generated in each language?  "Generic" services
   * are not specific to any particular RPC system.  They are generated by the
   * main code generators in each language (without additional plugins).
   * Generic services were the only kind of service generation supported by
   * early versions of proto2.
   *
   * Generic services are now considered deprecated in favor of using plugins
   * that generate code specific to your particular RPC system.  Therefore,
   * these default to false.  Old code which depends on generic services should
   * explicitly set them to true.
   * </pre>
   */
  public boolean getCcGenericServices() {
    return ccGenericServices_;
  }

  // optional bool java_generic_services = 17 [default = false];
  public static final int JAVA_GENERIC_SERVICES_FIELD_NUMBER = 17;
  private boolean javaGenericServices_;
  /**
   * <code>optional bool java_generic_services = 17 [default = false];</code>
   */
  public boolean hasJavaGenericServices() {
    return ((bitField0_ & 0x00000080) == 0x00000080);
  }
  /**
   * <code>optional bool java_generic_services = 17 [default = false];</code>
   */
  public boolean getJavaGenericServices() {
    return javaGenericServices_;
  }

  // optional bool py_generic_services = 18 [default = false];
  public static final int PY_GENERIC_SERVICES_FIELD_NUMBER = 18;
  private boolean pyGenericServices_;
  /**
   * <code>optional bool py_generic_services = 18 [default = false];</code>
   */
  public boolean hasPyGenericServices() {
    return ((bitField0_ & 0x00000100) == 0x00000100);
  }
  /**
   * <code>optional bool py_generic_services = 18 [default = false];</code>
   */
  public boolean getPyGenericServices() {
    return pyGenericServices_;
  }

  // repeated .google.protobuf.UninterpretedOption uninterpreted_option = 999;
  public static final int UNINTERPRETED_OPTION_FIELD_NUMBER = 999;
  private java.util.List<com.google.protobuf.UninterpretedOption> uninterpretedOption_;
  /**
   * <code>repeated .google.protobuf.UninterpretedOption uninterpreted_option = 999;</code>
   *
   * <pre>
   * The parser stores options it doesn't recognize here. See above.
   * </pre>
   */
  public java.util.List<com.google.protobuf.UninterpretedOption> getUninterpretedOptionList() {
    return uninterpretedOption_;
  }
  /**
   * <code>repeated .google.protobuf.UninterpretedOption uninterpreted_option = 999;</code>
   *
   * <pre>
   * The parser stores options it doesn't recognize here. See above.
   * </pre>
   */
  public java.util.List<? extends com.google.protobuf.UninterpretedOptionOrBuilder> 
      getUninterpretedOptionOrBuilderList() {
    return uninterpretedOption_;
  }
  /**
   * <code>repeated .google.protobuf.UninterpretedOption uninterpreted_option = 999;</code>
   *
   * <pre>
   * The parser stores options it doesn't recognize here. See above.
   * </pre>
   */
  public int getUninterpretedOptionCount() {
    return uninterpretedOption_.size();
  }
  /**
   * <code>repeated .google.protobuf.UninterpretedOption uninterpreted_option = 999;</code>
   *
   * <pre>
   * The parser stores options it doesn't recognize here. See above.
   * </pre>
   */
  public com.google.protobuf.UninterpretedOption getUninterpretedOption(int index) {
    return uninterpretedOption_.get(index);
  }
  /**
   * <code>repeated .google.protobuf.UninterpretedOption uninterpreted_option = 999;</code>
   *
   * <pre>
   * The parser stores options it doesn't recognize here. See above.
   * </pre>
   */
  public com.google.protobuf.UninterpretedOptionOrBuilder getUninterpretedOptionOrBuilder(
      int index) {
    return uninterpretedOption_.get(index);
  }

  private void initFields() {
    javaPackage_ = "";
    javaOuterClassname_ = "";
    javaMultipleFiles_ = false;
    javaGenerateEqualsAndHash_ = false;
    optimizeFor_ = com.google.protobuf.FileOptions.OptimizeMode.SPEED;
    goPackage_ = "";
    ccGenericServices_ = false;
    javaGenericServices_ = false;
    pyGenericServices_ = false;
    uninterpretedOption_ = java.util.Collections.emptyList();
  }
  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized != -1) return isInitialized == 1;

    for (int i = 0; i < getUninterpretedOptionCount(); i++) {
      if (!getUninterpretedOption(i).isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
    }
    if (!extensionsAreInitialized()) {
      memoizedIsInitialized = 0;
      return false;
    }
    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    getSerializedSize();
    com.google.protobuf.GeneratedMessage
      .ExtendableMessage<com.google.protobuf.FileOptions>.ExtensionWriter extensionWriter =
        newExtensionWriter();
    if (((bitField0_ & 0x00000001) == 0x00000001)) {
      output.writeBytes(1, getJavaPackageBytes());
    }
    if (((bitField0_ & 0x00000002) == 0x00000002)) {
      output.writeBytes(8, getJavaOuterClassnameBytes());
    }
    if (((bitField0_ & 0x00000010) == 0x00000010)) {
      output.writeEnum(9, optimizeFor_.getNumber());
    }
    if (((bitField0_ & 0x00000004) == 0x00000004)) {
      output.writeBool(10, javaMultipleFiles_);
    }
    if (((bitField0_ & 0x00000020) == 0x00000020)) {
      output.writeBytes(11, getGoPackageBytes());
    }
    if (((bitField0_ & 0x00000040) == 0x00000040)) {
      output.writeBool(16, ccGenericServices_);
    }
    if (((bitField0_ & 0x00000080) == 0x00000080)) {
      output.writeBool(17, javaGenericServices_);
    }
    if (((bitField0_ & 0x00000100) == 0x00000100)) {
      output.writeBool(18, pyGenericServices_);
    }
    if (((bitField0_ & 0x00000008) == 0x00000008)) {
      output.writeBool(20, javaGenerateEqualsAndHash_);
    }
    for (int i = 0; i < uninterpretedOption_.size(); i++) {
      output.writeMessage(999, uninterpretedOption_.get(i));
    }
    extensionWriter.writeUntil(536870912, output);
    getUnknownFields().writeTo(output);
  }

  private int memoizedSerializedSize = -1;
  public int getSerializedSize() {
    int size = memoizedSerializedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) == 0x00000001)) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(1, getJavaPackageBytes());
    }
    if (((bitField0_ & 0x00000002) == 0x00000002)) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(8, getJavaOuterClassnameBytes());
    }
    if (((bitField0_ & 0x00000010) == 0x00000010)) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(9, optimizeFor_.getNumber());
    }
    if (((bitField0_ & 0x00000004) == 0x00000004)) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(10, javaMultipleFiles_);
    }
    if (((bitField0_ & 0x00000020) == 0x00000020)) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(11, getGoPackageBytes());
    }
    if (((bitField0_ & 0x00000040) == 0x00000040)) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(16, ccGenericServices_);
    }
    if (((bitField0_ & 0x00000080) == 0x00000080)) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(17, javaGenericServices_);
    }
    if (((bitField0_ & 0x00000100) == 0x00000100)) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(18, pyGenericServices_);
    }
    if (((bitField0_ & 0x00000008) == 0x00000008)) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(20, javaGenerateEqualsAndHash_);
    }
    for (int i = 0; i < uninterpretedOption_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(999, uninterpretedOption_.get(i));
    }
    size += extensionsSerializedSize();
    size += getUnknownFields().getSerializedSize();
    memoizedSerializedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  protected java.lang.Object writeReplace()
      throws java.io.ObjectStreamException {
    return super.writeReplace();
  }

  public static com.google.protobuf.FileOptions parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.google.protobuf.FileOptions parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.google.protobuf.FileOptions parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.google.protobuf.FileOptions parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.google.protobuf.FileOptions parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return PARSER.parseFrom(input);
  }
  public static com.google.protobuf.FileOptions parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseFrom(input, extensionRegistry);
  }
  public static com.google.protobuf.FileOptions parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return PARSER.parseDelimitedFrom(input);
  }
  public static com.google.protobuf.FileOptions parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseDelimitedFrom(input, extensionRegistry);
  }
  public static com.google.protobuf.FileOptions parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return PARSER.parseFrom(input);
  }
  public static com.google.protobuf.FileOptions parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseFrom(input, extensionRegistry);
  }

  public static Builder newBuilder() { return Builder.create(); }
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder(com.google.protobuf.FileOptions prototype) {
    return newBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() { return newBuilder(this); }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code google.protobuf.FileOptions}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.ExtendableBuilder<
        com.google.protobuf.FileOptions, Builder> implements com.google.protobuf.FileOptionsOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.google.protobuf.DescriptorProtos.internal_static_google_protobuf_FileOptions_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.google.protobuf.DescriptorProtos.internal_static_google_protobuf_FileOptions_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.google.protobuf.FileOptions.class, com.google.protobuf.FileOptions.Builder.class);
    }

    // Construct using com.google.protobuf.FileOptions.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        getUninterpretedOptionFieldBuilder();
      }
    }
    private static Builder create() {
      return new Builder();
    }

    public Builder clear() {
      super.clear();
      javaPackage_ = "";
      bitField0_ = (bitField0_ & ~0x00000001);
      javaOuterClassname_ = "";
      bitField0_ = (bitField0_ & ~0x00000002);
      javaMultipleFiles_ = false;
      bitField0_ = (bitField0_ & ~0x00000004);
      javaGenerateEqualsAndHash_ = false;
      bitField0_ = (bitField0_ & ~0x00000008);
      optimizeFor_ = com.google.protobuf.FileOptions.OptimizeMode.SPEED;
      bitField0_ = (bitField0_ & ~0x00000010);
      goPackage_ = "";
      bitField0_ = (bitField0_ & ~0x00000020);
      ccGenericServices_ = false;
      bitField0_ = (bitField0_ & ~0x00000040);
      javaGenericServices_ = false;
      bitField0_ = (bitField0_ & ~0x00000080);
      pyGenericServices_ = false;
      bitField0_ = (bitField0_ & ~0x00000100);
      if (uninterpretedOptionBuilder_ == null) {
        uninterpretedOption_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000200);
      } else {
        uninterpretedOptionBuilder_.clear();
      }
      return this;
    }

    public Builder clone() {
      return create().mergeFrom(buildPartial());
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.google.protobuf.DescriptorProtos.internal_static_google_protobuf_FileOptions_descriptor;
    }

    public com.google.protobuf.FileOptions getDefaultInstanceForType() {
      return com.google.protobuf.FileOptions.getDefaultInstance();
    }

    public com.google.protobuf.FileOptions build() {
      com.google.protobuf.FileOptions result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.google.protobuf.FileOptions buildPartial() {
      com.google.protobuf.FileOptions result = new com.google.protobuf.FileOptions(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
        to_bitField0_ |= 0x00000001;
      }
      result.javaPackage_ = javaPackage_;
      if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
        to_bitField0_ |= 0x00000002;
      }
      result.javaOuterClassname_ = javaOuterClassname_;
      if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
        to_bitField0_ |= 0x00000004;
      }
      result.javaMultipleFiles_ = javaMultipleFiles_;
      if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
        to_bitField0_ |= 0x00000008;
      }
      result.javaGenerateEqualsAndHash_ = javaGenerateEqualsAndHash_;
      if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
        to_bitField0_ |= 0x00000010;
      }
      result.optimizeFor_ = optimizeFor_;
      if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
        to_bitField0_ |= 0x00000020;
      }
      result.goPackage_ = goPackage_;
      if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
        to_bitField0_ |= 0x00000040;
      }
      result.ccGenericServices_ = ccGenericServices_;
      if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
        to_bitField0_ |= 0x00000080;
      }
      result.javaGenericServices_ = javaGenericServices_;
      if (((from_bitField0_ & 0x00000100) == 0x00000100)) {
        to_bitField0_ |= 0x00000100;
      }
      result.pyGenericServices_ = pyGenericServices_;
      if (uninterpretedOptionBuilder_ == null) {
        if (((bitField0_ & 0x00000200) == 0x00000200)) {
          uninterpretedOption_ = java.util.Collections.unmodifiableList(uninterpretedOption_);
          bitField0_ = (bitField0_ & ~0x00000200);
        }
        result.uninterpretedOption_ = uninterpretedOption_;
      } else {
        result.uninterpretedOption_ = uninterpretedOptionBuilder_.build();
      }
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.google.protobuf.FileOptions) {
        return mergeFrom((com.google.protobuf.FileOptions)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.google.protobuf.FileOptions other) {
      if (other == com.google.protobuf.FileOptions.getDefaultInstance()) return this;
      if (other.hasJavaPackage()) {
        bitField0_ |= 0x00000001;
        javaPackage_ = other.javaPackage_;
        onChanged();
      }
      if (other.hasJavaOuterClassname()) {
        bitField0_ |= 0x00000002;
        javaOuterClassname_ = other.javaOuterClassname_;
        onChanged();
      }
      if (other.hasJavaMultipleFiles()) {
        setJavaMultipleFiles(other.getJavaMultipleFiles());
      }
      if (other.hasJavaGenerateEqualsAndHash()) {
        setJavaGenerateEqualsAndHash(other.getJavaGenerateEqualsAndHash());
      }
      if (other.hasOptimizeFor()) {
        setOptimizeFor(other.getOptimizeFor());
      }
      if (other.hasGoPackage()) {
        bitField0_ |= 0x00000020;
        goPackage_ = other.goPackage_;
        onChanged();
      }
      if (other.hasCcGenericServices()) {
        setCcGenericServices(other.getCcGenericServices());
      }
      if (other.hasJavaGenericServices()) {
        setJavaGenericServices(other.getJavaGenericServices());
      }
      if (other.hasPyGenericServices()) {
        setPyGenericServices(other.getPyGenericServices());
      }
      if (uninterpretedOptionBuilder_ == null) {
        if (!other.uninterpretedOption_.isEmpty()) {
          if (uninterpretedOption_.isEmpty()) {
            uninterpretedOption_ = other.uninterpretedOption_;
            bitField0_ = (bitField0_ & ~0x00000200);
          } else {
            ensureUninterpretedOptionIsMutable();
            uninterpretedOption_.addAll(other.uninterpretedOption_);
          }
          onChanged();
        }
      } else {
        if (!other.uninterpretedOption_.isEmpty()) {
          if (uninterpretedOptionBuilder_.isEmpty()) {
            uninterpretedOptionBuilder_.dispose();
            uninterpretedOptionBuilder_ = null;
            uninterpretedOption_ = other.uninterpretedOption_;
            bitField0_ = (bitField0_ & ~0x00000200);
            uninterpretedOptionBuilder_ = 
              com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                 getUninterpretedOptionFieldBuilder() : null;
          } else {
            uninterpretedOptionBuilder_.addAllMessages(other.uninterpretedOption_);
          }
        }
      }
      this.mergeExtensionFields(other);
      this.mergeUnknownFields(other.getUnknownFields());
      return this;
    }

    public final boolean isInitialized() {
      for (int i = 0; i < getUninterpretedOptionCount(); i++) {
        if (!getUninterpretedOption(i).isInitialized()) {
          
          return false;
        }
      }
      if (!extensionsAreInitialized()) {
        
        return false;
      }
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.google.protobuf.FileOptions parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.google.protobuf.FileOptions) e.getUnfinishedMessage();
        throw e;
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    // optional string java_package = 1;
    private java.lang.Object javaPackage_ = "";
    /**
     * <code>optional string java_package = 1;</code>
     *
     * <pre>
     * Sets the Java package where classes generated from this .proto will be
     * placed.  By default, the proto package is used, but this is often
     * inappropriate because proto packages do not normally start with backwards
     * domain names.
     * </pre>
     */
    public boolean hasJavaPackage() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional string java_package = 1;</code>
     *
     * <pre>
     * Sets the Java package where classes generated from this .proto will be
     * placed.  By default, the proto package is used, but this is often
     * inappropriate because proto packages do not normally start with backwards
     * domain names.
     * </pre>
     */
    public java.lang.String getJavaPackage() {
      java.lang.Object ref = javaPackage_;
      if (!(ref instanceof java.lang.String)) {
        java.lang.String s = ((com.google.protobuf.ByteString) ref)
            .toStringUtf8();
        javaPackage_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string java_package = 1;</code>
     *
     * <pre>
     * Sets the Java package where classes generated from this .proto will be
     * placed.  By default, the proto package is used, but this is often
     * inappropriate because proto packages do not normally start with backwards
     * domain names.
     * </pre>
     */
    public com.google.protobuf.ByteString
        getJavaPackageBytes() {
      java.lang.Object ref = javaPackage_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        javaPackage_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string java_package = 1;</code>
     *
     * <pre>
     * Sets the Java package where classes generated from this .proto will be
     * placed.  By default, the proto package is used, but this is often
     * inappropriate because proto packages do not normally start with backwards
     * domain names.
     * </pre>
     */
    public Builder setJavaPackage(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
      javaPackage_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string java_package = 1;</code>
     *
     * <pre>
     * Sets the Java package where classes generated from this .proto will be
     * placed.  By default, the proto package is used, but this is often
     * inappropriate because proto packages do not normally start with backwards
     * domain names.
     * </pre>
     */
    public Builder clearJavaPackage() {
      bitField0_ = (bitField0_ & ~0x00000001);
      javaPackage_ = getDefaultInstance().getJavaPackage();
      onChanged();
      return this;
    }
    /**
     * <code>optional string java_package = 1;</code>
     *
     * <pre>
     * Sets the Java package where classes generated from this .proto will be
     * placed.  By default, the proto package is used, but this is often
     * inappropriate because proto packages do not normally start with backwards
     * domain names.
     * </pre>
     */
    public Builder setJavaPackageBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
      javaPackage_ = value;
      onChanged();
      return this;
    }

    // optional string java_outer_classname = 8;
    private java.lang.Object javaOuterClassname_ = "";
    /**
     * <code>optional string java_outer_classname = 8;</code>
     *
     * <pre>
     * If set, all the classes from the .proto file are wrapped in a single
     * outer class with the given name.  This applies to both Proto1
     * (equivalent to the old "--one_java_file" option) and Proto2 (where
     * a .proto always translates to a single class, but you may want to
     * explicitly choose the class name).
     * </pre>
     */
    public boolean hasJavaOuterClassname() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string java_outer_classname = 8;</code>
     *
     * <pre>
     * If set, all the classes from the .proto file are wrapped in a single
     * outer class with the given name.  This applies to both Proto1
     * (equivalent to the old "--one_java_file" option) and Proto2 (where
     * a .proto always translates to a single class, but you may want to
     * explicitly choose the class name).
     * </pre>
     */
    public java.lang.String getJavaOuterClassname() {
      java.lang.Object ref = javaOuterClassname_;
      if (!(ref instanceof java.lang.String)) {
        java.lang.String s = ((com.google.protobuf.ByteString) ref)
            .toStringUtf8();
        javaOuterClassname_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string java_outer_classname = 8;</code>
     *
     * <pre>
     * If set, all the classes from the .proto file are wrapped in a single
     * outer class with the given name.  This applies to both Proto1
     * (equivalent to the old "--one_java_file" option) and Proto2 (where
     * a .proto always translates to a single class, but you may want to
     * explicitly choose the class name).
     * </pre>
     */
    public com.google.protobuf.ByteString
        getJavaOuterClassnameBytes() {
      java.lang.Object ref = javaOuterClassname_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        javaOuterClassname_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string java_outer_classname = 8;</code>
     *
     * <pre>
     * If set, all the classes from the .proto file are wrapped in a single
     * outer class with the given name.  This applies to both Proto1
     * (equivalent to the old "--one_java_file" option) and Proto2 (where
     * a .proto always translates to a single class, but you may want to
     * explicitly choose the class name).
     * </pre>
     */
    public Builder setJavaOuterClassname(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
      javaOuterClassname_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string java_outer_classname = 8;</code>
     *
     * <pre>
     * If set, all the classes from the .proto file are wrapped in a single
     * outer class with the given name.  This applies to both Proto1
     * (equivalent to the old "--one_java_file" option) and Proto2 (where
     * a .proto always translates to a single class, but you may want to
     * explicitly choose the class name).
     * </pre>
     */
    public Builder clearJavaOuterClassname() {
      bitField0_ = (bitField0_ & ~0x00000002);
      javaOuterClassname_ = getDefaultInstance().getJavaOuterClassname();
      onChanged();
      return this;
    }
    /**
     * <code>optional string java_outer_classname = 8;</code>
     *
     * <pre>
     * If set, all the classes from the .proto file are wrapped in a single
     * outer class with the given name.  This applies to both Proto1
     * (equivalent to the old "--one_java_file" option) and Proto2 (where
     * a .proto always translates to a single class, but you may want to
     * explicitly choose the class name).
     * </pre>
     */
    public Builder setJavaOuterClassnameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
      javaOuterClassname_ = value;
      onChanged();
      return this;
    }

    // optional bool java_multiple_files = 10 [default = false];
    private boolean javaMultipleFiles_ ;
    /**
     * <code>optional bool java_multiple_files = 10 [default = false];</code>
     *
     * <pre>
     * If set true, then the Java code generator will generate a separate .java
     * file for each top-level message, enum, and service defined in the .proto
     * file.  Thus, these types will *not* be nested inside the outer class
     * named by java_outer_classname.  However, the outer class will still be
     * generated to contain the file's getDescriptor() method as well as any
     * top-level extensions defined in the file.
     * </pre>
     */
    public boolean hasJavaMultipleFiles() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional bool java_multiple_files = 10 [default = false];</code>
     *
     * <pre>
     * If set true, then the Java code generator will generate a separate .java
     * file for each top-level message, enum, and service defined in the .proto
     * file.  Thus, these types will *not* be nested inside the outer class
     * named by java_outer_classname.  However, the outer class will still be
     * generated to contain the file's getDescriptor() method as well as any
     * top-level extensions defined in the file.
     * </pre>
     */
    public boolean getJavaMultipleFiles() {
      return javaMultipleFiles_;
    }
    /**
     * <code>optional bool java_multiple_files = 10 [default = false];</code>
     *
     * <pre>
     * If set true, then the Java code generator will generate a separate .java
     * file for each top-level message, enum, and service defined in the .proto
     * file.  Thus, these types will *not* be nested inside the outer class
     * named by java_outer_classname.  However, the outer class will still be
     * generated to contain the file's getDescriptor() method as well as any
     * top-level extensions defined in the file.
     * </pre>
     */
    public Builder setJavaMultipleFiles(boolean value) {
      bitField0_ |= 0x00000004;
      javaMultipleFiles_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional bool java_multiple_files = 10 [default = false];</code>
     *
     * <pre>
     * If set true, then the Java code generator will generate a separate .java
     * file for each top-level message, enum, and service defined in the .proto
     * file.  Thus, these types will *not* be nested inside the outer class
     * named by java_outer_classname.  However, the outer class will still be
     * generated to contain the file's getDescriptor() method as well as any
     * top-level extensions defined in the file.
     * </pre>
     */
    public Builder clearJavaMultipleFiles() {
      bitField0_ = (bitField0_ & ~0x00000004);
      javaMultipleFiles_ = false;
      onChanged();
      return this;
    }

    // optional bool java_generate_equals_and_hash = 20 [default = false];
    private boolean javaGenerateEqualsAndHash_ ;
    /**
     * <code>optional bool java_generate_equals_and_hash = 20 [default = false];</code>
     *
     * <pre>
     * If set true, then the Java code generator will generate equals() and
     * hashCode() methods for all messages defined in the .proto file. This is
     * purely a speed optimization, as the AbstractMessage base class includes
     * reflection-based implementations of these methods.
     * </pre>
     */
    public boolean hasJavaGenerateEqualsAndHash() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional bool java_generate_equals_and_hash = 20 [default = false];</code>
     *
     * <pre>
     * If set true, then the Java code generator will generate equals() and
     * hashCode() methods for all messages defined in the .proto file. This is
     * purely a speed optimization, as the AbstractMessage base class includes
     * reflection-based implementations of these methods.
     * </pre>
     */
    public boolean getJavaGenerateEqualsAndHash() {
      return javaGenerateEqualsAndHash_;
    }
    /**
     * <code>optional bool java_generate_equals_and_hash = 20 [default = false];</code>
     *
     * <pre>
     * If set true, then the Java code generator will generate equals() and
     * hashCode() methods for all messages defined in the .proto file. This is
     * purely a speed optimization, as the AbstractMessage base class includes
     * reflection-based implementations of these methods.
     * </pre>
     */
    public Builder setJavaGenerateEqualsAndHash(boolean value) {
      bitField0_ |= 0x00000008;
      javaGenerateEqualsAndHash_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional bool java_generate_equals_and_hash = 20 [default = false];</code>
     *
     * <pre>
     * If set true, then the Java code generator will generate equals() and
     * hashCode() methods for all messages defined in the .proto file. This is
     * purely a speed optimization, as the AbstractMessage base class includes
     * reflection-based implementations of these methods.
     * </pre>
     */
    public Builder clearJavaGenerateEqualsAndHash() {
      bitField0_ = (bitField0_ & ~0x00000008);
      javaGenerateEqualsAndHash_ = false;
      onChanged();
      return this;
    }

    // optional .google.protobuf.FileOptions.OptimizeMode optimize_for = 9 [default = SPEED];
    private com.google.protobuf.FileOptions.OptimizeMode optimizeFor_ = com.google.protobuf.FileOptions.OptimizeMode.SPEED;
    /**
     * <code>optional .google.protobuf.FileOptions.OptimizeMode optimize_for = 9 [default = SPEED];</code>
     */
    public boolean hasOptimizeFor() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional .google.protobuf.FileOptions.OptimizeMode optimize_for = 9 [default = SPEED];</code>
     */
    public com.google.protobuf.FileOptions.OptimizeMode getOptimizeFor() {
      return optimizeFor_;
    }
    /**
     * <code>optional .google.protobuf.FileOptions.OptimizeMode optimize_for = 9 [default = SPEED];</code>
     */
    public Builder setOptimizeFor(com.google.protobuf.FileOptions.OptimizeMode value) {
      if (value == null) {
        throw new NullPointerException();
      }
      bitField0_ |= 0x00000010;
      optimizeFor_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional .google.protobuf.FileOptions.OptimizeMode optimize_for = 9 [default = SPEED];</code>
     */
    public Builder clearOptimizeFor() {
      bitField0_ = (bitField0_ & ~0x00000010);
      optimizeFor_ = com.google.protobuf.FileOptions.OptimizeMode.SPEED;
      onChanged();
      return this;
    }

    // optional string go_package = 11;
    private java.lang.Object goPackage_ = "";
    /**
     * <code>optional string go_package = 11;</code>
     *
     * <pre>
     * Sets the Go package where structs generated from this .proto will be
     * placed.  There is no default.
     * </pre>
     */
    public boolean hasGoPackage() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>optional string go_package = 11;</code>
     *
     * <pre>
     * Sets the Go package where structs generated from this .proto will be
     * placed.  There is no default.
     * </pre>
     */
    public java.lang.String getGoPackage() {
      java.lang.Object ref = goPackage_;
      if (!(ref instanceof java.lang.String)) {
        java.lang.String s = ((com.google.protobuf.ByteString) ref)
            .toStringUtf8();
        goPackage_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string go_package = 11;</code>
     *
     * <pre>
     * Sets the Go package where structs generated from this .proto will be
     * placed.  There is no default.
     * </pre>
     */
    public com.google.protobuf.ByteString
        getGoPackageBytes() {
      java.lang.Object ref = goPackage_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        goPackage_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string go_package = 11;</code>
     *
     * <pre>
     * Sets the Go package where structs generated from this .proto will be
     * placed.  There is no default.
     * </pre>
     */
    public Builder setGoPackage(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
      goPackage_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string go_package = 11;</code>
     *
     * <pre>
     * Sets the Go package where structs generated from this .proto will be
     * placed.  There is no default.
     * </pre>
     */
    public Builder clearGoPackage() {
      bitField0_ = (bitField0_ & ~0x00000020);
      goPackage_ = getDefaultInstance().getGoPackage();
      onChanged();
      return this;
    }
    /**
     * <code>optional string go_package = 11;</code>
     *
     * <pre>
     * Sets the Go package where structs generated from this .proto will be
     * placed.  There is no default.
     * </pre>
     */
    public Builder setGoPackageBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
      goPackage_ = value;
      onChanged();
      return this;
    }

    // optional bool cc_generic_services = 16 [default = false];
    private boolean ccGenericServices_ ;
    /**
     * <code>optional bool cc_generic_services = 16 [default = false];</code>
     *
     * <pre>
     * Should generic services be generated in each language?  "Generic" services
     * are not specific to any particular RPC system.  They are generated by the
     * main code generators in each language (without additional plugins).
     * Generic services were the only kind of service generation supported by
     * early versions of proto2.
     *
     * Generic services are now considered deprecated in favor of using plugins
     * that generate code specific to your particular RPC system.  Therefore,
     * these default to false.  Old code which depends on generic services should
     * explicitly set them to true.
     * </pre>
     */
    public boolean hasCcGenericServices() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    /**
     * <code>optional bool cc_generic_services = 16 [default = false];</code>
     *
     * <pre>
     * Should generic services be generated in each language?  "Generic" services
     * are not specific to any particular RPC system.  They are generated by the
     * main code generators in each language (without additional plugins).
     * Generic services were the only kind of service generation supported by
     * early versions of proto2.
     *
     * Generic services are now considered deprecated in favor of using plugins
     * that generate code specific to your particular RPC system.  Therefore,
     * these default to false.  Old code which depends on generic services should
     * explicitly set them to true.
     * </pre>
     */
    public boolean getCcGenericServices() {
      return ccGenericServices_;
    }
    /**
     * <code>optional bool cc_generic_services = 16 [default = false];</code>
     *
     * <pre>
     * Should generic services be generated in each language?  "Generic" services
     * are not specific to any particular RPC system.  They are generated by the
     * main code generators in each language (without additional plugins).
     * Generic services were the only kind of service generation supported by
     * early versions of proto2.
     *
     * Generic services are now considered deprecated in favor of using plugins
     * that generate code specific to your particular RPC system.  Therefore,
     * these default to false.  Old code which depends on generic services should
     * explicitly set them to true.
     * </pre>
     */
    public Builder setCcGenericServices(boolean value) {
      bitField0_ |= 0x00000040;
      ccGenericServices_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional bool cc_generic_services = 16 [default = false];</code>
     *
     * <pre>
     * Should generic services be generated in each language?  "Generic" services
     * are not specific to any particular RPC system.  They are generated by the
     * main code generators in each language (without additional plugins).
     * Generic services were the only kind of service generation supported by
     * early versions of proto2.
     *
     * Generic services are now considered deprecated in favor of using plugins
     * that generate code specific to your particular RPC system.  Therefore,
     * these default to false.  Old code which depends on generic services should
     * explicitly set them to true.
     * </pre>
     */
    public Builder clearCcGenericServices() {
      bitField0_ = (bitField0_ & ~0x00000040);
      ccGenericServices_ = false;
      onChanged();
      return this;
    }

    // optional bool java_generic_services = 17 [default = false];
    private boolean javaGenericServices_ ;
    /**
     * <code>optional bool java_generic_services = 17 [default = false];</code>
     */
    public boolean hasJavaGenericServices() {
      return ((bitField0_ & 0x00000080) == 0x00000080);
    }
    /**
     * <code>optional bool java_generic_services = 17 [default = false];</code>
     */
    public boolean getJavaGenericServices() {
      return javaGenericServices_;
    }
    /**
     * <code>optional bool java_generic_services = 17 [default = false];</code>
     */
    public Builder setJavaGenericServices(boolean value) {
      bitField0_ |= 0x00000080;
      javaGenericServices_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional bool java_generic_services = 17 [default = false];</code>
     */
    public Builder clearJavaGenericServices() {
      bitField0_ = (bitField0_ & ~0x00000080);
      javaGenericServices_ = false;
      onChanged();
      return this;
    }

    // optional bool py_generic_services = 18 [default = false];
    private boolean pyGenericServices_ ;
    /**
     * <code>optional bool py_generic_services = 18 [default = false];</code>
     */
    public boolean hasPyGenericServices() {
      return ((bitField0_ & 0x00000100) == 0x00000100);
    }
    /**
     * <code>optional bool py_generic_services = 18 [default = false];</code>
     */
    public boolean getPyGenericServices() {
      return pyGenericServices_;
    }
    /**
     * <code>optional bool py_generic_services = 18 [default = false];</code>
     */
    public Builder setPyGenericServices(boolean value) {
      bitField0_ |= 0x00000100;
      pyGenericServices_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional bool py_generic_services = 18 [default = false];</code>
     */
    public Builder clearPyGenericServices() {
      bitField0_ = (bitField0_ & ~0x00000100);
      pyGenericServices_ = false;
      onChanged();
      return this;
    }

    // repeated .google.protobuf.UninterpretedOption uninterpreted_option = 999;
    private java.util.List<com.google.protobuf.UninterpretedOption> uninterpretedOption_ =
      java.util.Collections.emptyList();
    private void ensureUninterpretedOptionIsMutable() {
      if (!((bitField0_ & 0x00000200) == 0x00000200)) {
        uninterpretedOption_ = new java.util.ArrayList<com.google.protobuf.UninterpretedOption>(uninterpretedOption_);
        bitField0_ |= 0x00000200;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilder<
        com.google.protobuf.UninterpretedOption, com.google.protobuf.UninterpretedOption.Builder, com.google.protobuf.UninterpretedOptionOrBuilder> uninterpretedOptionBuilder_;

    /**
     * <code>repeated .google.protobuf.UninterpretedOption uninterpreted_option = 999;</code>
     *
     * <pre>
     * The parser stores options it doesn't recognize here. See above.
     * </pre>
     */
    public java.util.List<com.google.protobuf.UninterpretedOption> getUninterpretedOptionList() {
      if (uninterpretedOptionBuilder_ == null) {
        return java.util.Collections.unmodifiableList(uninterpretedOption_);
      } else {
        return uninterpretedOptionBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .google.protobuf.UninterpretedOption uninterpreted_option = 999;</code>
     *
     * <pre>
     * The parser stores options it doesn't recognize here. See above.
     * </pre>
     */
    public int getUninterpretedOptionCount() {
      if (uninterpretedOptionBuilder_ == null) {
        return uninterpretedOption_.size();
      } else {
        return uninterpretedOptionBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .google.protobuf.UninterpretedOption uninterpreted_option = 999;</code>
     *
     * <pre>
     * The parser stores options it doesn't recognize here. See above.
     * </pre>
     */
    public com.google.protobuf.UninterpretedOption getUninterpretedOption(int index) {
      if (uninterpretedOptionBuilder_ == null) {
        return uninterpretedOption_.get(index);
      } else {
        return uninterpretedOptionBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .google.protobuf.UninterpretedOption uninterpreted_option = 999;</code>
     *
     * <pre>
     * The parser stores options it doesn't recognize here. See above.
     * </pre>
     */
    public Builder setUninterpretedOption(
        int index, com.google.protobuf.UninterpretedOption value) {
      if (uninterpretedOptionBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureUninterpretedOptionIsMutable();
        uninterpretedOption_.set(index, value);
        onChanged();
      } else {
        uninterpretedOptionBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .google.protobuf.UninterpretedOption uninterpreted_option = 999;</code>
     *
     * <pre>
     * The parser stores options it doesn't recognize here. See above.
     * </pre>
     */
    public Builder setUninterpretedOption(
        int index, com.google.protobuf.UninterpretedOption.Builder builderForValue) {
      if (uninterpretedOptionBuilder_ == null) {
        ensureUninterpretedOptionIsMutable();
        uninterpretedOption_.set(index, builderForValue.build());
        onChanged();
      } else {
        uninterpretedOptionBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .google.protobuf.UninterpretedOption uninterpreted_option = 999;</code>
     *
     * <pre>
     * The parser stores options it doesn't recognize here. See above.
     * </pre>
     */
    public Builder addUninterpretedOption(com.google.protobuf.UninterpretedOption value) {
      if (uninterpretedOptionBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureUninterpretedOptionIsMutable();
        uninterpretedOption_.add(value);
        onChanged();
      } else {
        uninterpretedOptionBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .google.protobuf.UninterpretedOption uninterpreted_option = 999;</code>
     *
     * <pre>
     * The parser stores options it doesn't recognize here. See above.
     * </pre>
     */
    public Builder addUninterpretedOption(
        int index, com.google.protobuf.UninterpretedOption value) {
      if (uninterpretedOptionBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureUninterpretedOptionIsMutable();
        uninterpretedOption_.add(index, value);
        onChanged();
      } else {
        uninterpretedOptionBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .google.protobuf.UninterpretedOption uninterpreted_option = 999;</code>
     *
     * <pre>
     * The parser stores options it doesn't recognize here. See above.
     * </pre>
     */
    public Builder addUninterpretedOption(
        com.google.protobuf.UninterpretedOption.Builder builderForValue) {
      if (uninterpretedOptionBuilder_ == null) {
        ensureUninterpretedOptionIsMutable();
        uninterpretedOption_.add(builderForValue.build());
        onChanged();
      } else {
        uninterpretedOptionBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .google.protobuf.UninterpretedOption uninterpreted_option = 999;</code>
     *
     * <pre>
     * The parser stores options it doesn't recognize here. See above.
     * </pre>
     */
    public Builder addUninterpretedOption(
        int index, com.google.protobuf.UninterpretedOption.Builder builderForValue) {
      if (uninterpretedOptionBuilder_ == null) {
        ensureUninterpretedOptionIsMutable();
        uninterpretedOption_.add(index, builderForValue.build());
        onChanged();
      } else {
        uninterpretedOptionBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .google.protobuf.UninterpretedOption uninterpreted_option = 999;</code>
     *
     * <pre>
     * The parser stores options it doesn't recognize here. See above.
     * </pre>
     */
    public Builder addAllUninterpretedOption(
        java.lang.Iterable<? extends com.google.protobuf.UninterpretedOption> values) {
      if (uninterpretedOptionBuilder_ == null) {
        ensureUninterpretedOptionIsMutable();
        super.addAll(values, uninterpretedOption_);
        onChanged();
      } else {
        uninterpretedOptionBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .google.protobuf.UninterpretedOption uninterpreted_option = 999;</code>
     *
     * <pre>
     * The parser stores options it doesn't recognize here. See above.
     * </pre>
     */
    public Builder clearUninterpretedOption() {
      if (uninterpretedOptionBuilder_ == null) {
        uninterpretedOption_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000200);
        onChanged();
      } else {
        uninterpretedOptionBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .google.protobuf.UninterpretedOption uninterpreted_option = 999;</code>
     *
     * <pre>
     * The parser stores options it doesn't recognize here. See above.
     * </pre>
     */
    public Builder removeUninterpretedOption(int index) {
      if (uninterpretedOptionBuilder_ == null) {
        ensureUninterpretedOptionIsMutable();
        uninterpretedOption_.remove(index);
        onChanged();
      } else {
        uninterpretedOptionBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .google.protobuf.UninterpretedOption uninterpreted_option = 999;</code>
     *
     * <pre>
     * The parser stores options it doesn't recognize here. See above.
     * </pre>
     */
    public com.google.protobuf.UninterpretedOption.Builder getUninterpretedOptionBuilder(
        int index) {
      return getUninterpretedOptionFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .google.protobuf.UninterpretedOption uninterpreted_option = 999;</code>
     *
     * <pre>
     * The parser stores options it doesn't recognize here. See above.
     * </pre>
     */
    public com.google.protobuf.UninterpretedOptionOrBuilder getUninterpretedOptionOrBuilder(
        int index) {
      if (uninterpretedOptionBuilder_ == null) {
        return uninterpretedOption_.get(index);  } else {
        return uninterpretedOptionBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .google.protobuf.UninterpretedOption uninterpreted_option = 999;</code>
     *
     * <pre>
     * The parser stores options it doesn't recognize here. See above.
     * </pre>
     */
    public java.util.List<? extends com.google.protobuf.UninterpretedOptionOrBuilder> 
         getUninterpretedOptionOrBuilderList() {
      if (uninterpretedOptionBuilder_ != null) {
        return uninterpretedOptionBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(uninterpretedOption_);
      }
    }
    /**
     * <code>repeated .google.protobuf.UninterpretedOption uninterpreted_option = 999;</code>
     *
     * <pre>
     * The parser stores options it doesn't recognize here. See above.
     * </pre>
     */
    public com.google.protobuf.UninterpretedOption.Builder addUninterpretedOptionBuilder() {
      return getUninterpretedOptionFieldBuilder().addBuilder(
          com.google.protobuf.UninterpretedOption.getDefaultInstance());
    }
    /**
     * <code>repeated .google.protobuf.UninterpretedOption uninterpreted_option = 999;</code>
     *
     * <pre>
     * The parser stores options it doesn't recognize here. See above.
     * </pre>
     */
    public com.google.protobuf.UninterpretedOption.Builder addUninterpretedOptionBuilder(
        int index) {
      return getUninterpretedOptionFieldBuilder().addBuilder(
          index, com.google.protobuf.UninterpretedOption.getDefaultInstance());
    }
    /**
     * <code>repeated .google.protobuf.UninterpretedOption uninterpreted_option = 999;</code>
     *
     * <pre>
     * The parser stores options it doesn't recognize here. See above.
     * </pre>
     */
    public java.util.List<com.google.protobuf.UninterpretedOption.Builder> 
         getUninterpretedOptionBuilderList() {
      return getUninterpretedOptionFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilder<
        com.google.protobuf.UninterpretedOption, com.google.protobuf.UninterpretedOption.Builder, com.google.protobuf.UninterpretedOptionOrBuilder> 
        getUninterpretedOptionFieldBuilder() {
      if (uninterpretedOptionBuilder_ == null) {
        uninterpretedOptionBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
            com.google.protobuf.UninterpretedOption, com.google.protobuf.UninterpretedOption.Builder, com.google.protobuf.UninterpretedOptionOrBuilder>(
                uninterpretedOption_,
                ((bitField0_ & 0x00000200) == 0x00000200),
                getParentForChildren(),
                isClean());
        uninterpretedOption_ = null;
      }
      return uninterpretedOptionBuilder_;
    }

    // @@protoc_insertion_point(builder_scope:google.protobuf.FileOptions)
  }

  static {
    defaultInstance = new FileOptions(true);
    defaultInstance.initFields();
  }

  // @@protoc_insertion_point(class_scope:google.protobuf.FileOptions)
}

