// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: descriptor.proto

package com.google.protobuf;

public interface FileDescriptorProtoOrBuilder
    extends com.google.protobuf.MessageOrBuilder {

  // optional string name = 1;
  /**
   * <code>optional string name = 1;</code>
   *
   * <pre>
   * file name, relative to root of source tree
   * </pre>
   */
  boolean hasName();
  /**
   * <code>optional string name = 1;</code>
   *
   * <pre>
   * file name, relative to root of source tree
   * </pre>
   */
  java.lang.String getName();
  /**
   * <code>optional string name = 1;</code>
   *
   * <pre>
   * file name, relative to root of source tree
   * </pre>
   */
  com.google.protobuf.ByteString
      getNameBytes();

  // optional string package = 2;
  /**
   * <code>optional string package = 2;</code>
   *
   * <pre>
   * e.g. "foo", "foo.bar", etc.
   * </pre>
   */
  boolean hasPackage();
  /**
   * <code>optional string package = 2;</code>
   *
   * <pre>
   * e.g. "foo", "foo.bar", etc.
   * </pre>
   */
  java.lang.String getPackage();
  /**
   * <code>optional string package = 2;</code>
   *
   * <pre>
   * e.g. "foo", "foo.bar", etc.
   * </pre>
   */
  com.google.protobuf.ByteString
      getPackageBytes();

  // repeated string dependency = 3;
  /**
   * <code>repeated string dependency = 3;</code>
   *
   * <pre>
   * Names of files imported by this file.
   * </pre>
   */
  java.util.List<java.lang.String>
  getDependencyList();
  /**
   * <code>repeated string dependency = 3;</code>
   *
   * <pre>
   * Names of files imported by this file.
   * </pre>
   */
  int getDependencyCount();
  /**
   * <code>repeated string dependency = 3;</code>
   *
   * <pre>
   * Names of files imported by this file.
   * </pre>
   */
  java.lang.String getDependency(int index);
  /**
   * <code>repeated string dependency = 3;</code>
   *
   * <pre>
   * Names of files imported by this file.
   * </pre>
   */
  com.google.protobuf.ByteString
      getDependencyBytes(int index);

  // repeated int32 public_dependency = 10;
  /**
   * <code>repeated int32 public_dependency = 10;</code>
   *
   * <pre>
   * Indexes of the public imported files in the dependency list above.
   * </pre>
   */
  java.util.List<java.lang.Integer> getPublicDependencyList();
  /**
   * <code>repeated int32 public_dependency = 10;</code>
   *
   * <pre>
   * Indexes of the public imported files in the dependency list above.
   * </pre>
   */
  int getPublicDependencyCount();
  /**
   * <code>repeated int32 public_dependency = 10;</code>
   *
   * <pre>
   * Indexes of the public imported files in the dependency list above.
   * </pre>
   */
  int getPublicDependency(int index);

  // repeated int32 weak_dependency = 11;
  /**
   * <code>repeated int32 weak_dependency = 11;</code>
   *
   * <pre>
   * Indexes of the weak imported files in the dependency list.
   * For Google-internal migration only. Do not use.
   * </pre>
   */
  java.util.List<java.lang.Integer> getWeakDependencyList();
  /**
   * <code>repeated int32 weak_dependency = 11;</code>
   *
   * <pre>
   * Indexes of the weak imported files in the dependency list.
   * For Google-internal migration only. Do not use.
   * </pre>
   */
  int getWeakDependencyCount();
  /**
   * <code>repeated int32 weak_dependency = 11;</code>
   *
   * <pre>
   * Indexes of the weak imported files in the dependency list.
   * For Google-internal migration only. Do not use.
   * </pre>
   */
  int getWeakDependency(int index);

  // repeated .google.protobuf.DescriptorProto message_type = 4;
  /**
   * <code>repeated .google.protobuf.DescriptorProto message_type = 4;</code>
   *
   * <pre>
   * All top-level definitions in this file.
   * </pre>
   */
  java.util.List<com.google.protobuf.DescriptorProto> 
      getMessageTypeList();
  /**
   * <code>repeated .google.protobuf.DescriptorProto message_type = 4;</code>
   *
   * <pre>
   * All top-level definitions in this file.
   * </pre>
   */
  com.google.protobuf.DescriptorProto getMessageType(int index);
  /**
   * <code>repeated .google.protobuf.DescriptorProto message_type = 4;</code>
   *
   * <pre>
   * All top-level definitions in this file.
   * </pre>
   */
  int getMessageTypeCount();
  /**
   * <code>repeated .google.protobuf.DescriptorProto message_type = 4;</code>
   *
   * <pre>
   * All top-level definitions in this file.
   * </pre>
   */
  java.util.List<? extends com.google.protobuf.DescriptorProtoOrBuilder> 
      getMessageTypeOrBuilderList();
  /**
   * <code>repeated .google.protobuf.DescriptorProto message_type = 4;</code>
   *
   * <pre>
   * All top-level definitions in this file.
   * </pre>
   */
  com.google.protobuf.DescriptorProtoOrBuilder getMessageTypeOrBuilder(
      int index);

  // repeated .google.protobuf.EnumDescriptorProto enum_type = 5;
  /**
   * <code>repeated .google.protobuf.EnumDescriptorProto enum_type = 5;</code>
   */
  java.util.List<com.google.protobuf.EnumDescriptorProto> 
      getEnumTypeList();
  /**
   * <code>repeated .google.protobuf.EnumDescriptorProto enum_type = 5;</code>
   */
  com.google.protobuf.EnumDescriptorProto getEnumType(int index);
  /**
   * <code>repeated .google.protobuf.EnumDescriptorProto enum_type = 5;</code>
   */
  int getEnumTypeCount();
  /**
   * <code>repeated .google.protobuf.EnumDescriptorProto enum_type = 5;</code>
   */
  java.util.List<? extends com.google.protobuf.EnumDescriptorProtoOrBuilder> 
      getEnumTypeOrBuilderList();
  /**
   * <code>repeated .google.protobuf.EnumDescriptorProto enum_type = 5;</code>
   */
  com.google.protobuf.EnumDescriptorProtoOrBuilder getEnumTypeOrBuilder(
      int index);

  // repeated .google.protobuf.ServiceDescriptorProto service = 6;
  /**
   * <code>repeated .google.protobuf.ServiceDescriptorProto service = 6;</code>
   */
  java.util.List<com.google.protobuf.ServiceDescriptorProto> 
      getServiceList();
  /**
   * <code>repeated .google.protobuf.ServiceDescriptorProto service = 6;</code>
   */
  com.google.protobuf.ServiceDescriptorProto getService(int index);
  /**
   * <code>repeated .google.protobuf.ServiceDescriptorProto service = 6;</code>
   */
  int getServiceCount();
  /**
   * <code>repeated .google.protobuf.ServiceDescriptorProto service = 6;</code>
   */
  java.util.List<? extends com.google.protobuf.ServiceDescriptorProtoOrBuilder> 
      getServiceOrBuilderList();
  /**
   * <code>repeated .google.protobuf.ServiceDescriptorProto service = 6;</code>
   */
  com.google.protobuf.ServiceDescriptorProtoOrBuilder getServiceOrBuilder(
      int index);

  // repeated .google.protobuf.FieldDescriptorProto extension = 7;
  /**
   * <code>repeated .google.protobuf.FieldDescriptorProto extension = 7;</code>
   */
  java.util.List<com.google.protobuf.FieldDescriptorProto> 
      getExtensionList();
  /**
   * <code>repeated .google.protobuf.FieldDescriptorProto extension = 7;</code>
   */
  com.google.protobuf.FieldDescriptorProto getExtension(int index);
  /**
   * <code>repeated .google.protobuf.FieldDescriptorProto extension = 7;</code>
   */
  int getExtensionCount();
  /**
   * <code>repeated .google.protobuf.FieldDescriptorProto extension = 7;</code>
   */
  java.util.List<? extends com.google.protobuf.FieldDescriptorProtoOrBuilder> 
      getExtensionOrBuilderList();
  /**
   * <code>repeated .google.protobuf.FieldDescriptorProto extension = 7;</code>
   */
  com.google.protobuf.FieldDescriptorProtoOrBuilder getExtensionOrBuilder(
      int index);

  // optional .google.protobuf.FileOptions options = 8;
  /**
   * <code>optional .google.protobuf.FileOptions options = 8;</code>
   */
  boolean hasOptions();
  /**
   * <code>optional .google.protobuf.FileOptions options = 8;</code>
   */
  com.google.protobuf.FileOptions getOptions();
  /**
   * <code>optional .google.protobuf.FileOptions options = 8;</code>
   */
  com.google.protobuf.FileOptionsOrBuilder getOptionsOrBuilder();

  // optional .google.protobuf.SourceCodeInfo source_code_info = 9;
  /**
   * <code>optional .google.protobuf.SourceCodeInfo source_code_info = 9;</code>
   *
   * <pre>
   * This field contains optional information about the original source code.
   * You may safely remove this entire field whithout harming runtime
   * functionality of the descriptors -- the information is needed only by
   * development tools.
   * </pre>
   */
  boolean hasSourceCodeInfo();
  /**
   * <code>optional .google.protobuf.SourceCodeInfo source_code_info = 9;</code>
   *
   * <pre>
   * This field contains optional information about the original source code.
   * You may safely remove this entire field whithout harming runtime
   * functionality of the descriptors -- the information is needed only by
   * development tools.
   * </pre>
   */
  com.google.protobuf.SourceCodeInfo getSourceCodeInfo();
  /**
   * <code>optional .google.protobuf.SourceCodeInfo source_code_info = 9;</code>
   *
   * <pre>
   * This field contains optional information about the original source code.
   * You may safely remove this entire field whithout harming runtime
   * functionality of the descriptors -- the information is needed only by
   * development tools.
   * </pre>
   */
  com.google.protobuf.SourceCodeInfoOrBuilder getSourceCodeInfoOrBuilder();
}
