// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: descriptor.proto

package com.google.protobuf;

/**
 * Protobuf type {@code google.protobuf.ServiceOptions}
 */
public  final class ServiceOptions extends
    com.google.protobuf.GeneratedMessage.ExtendableMessage<
      ServiceOptions> implements ServiceOptionsOrBuilder {
  // Use ServiceOptions.newBuilder() to construct.
  private ServiceOptions(com.google.protobuf.GeneratedMessage.ExtendableBuilder<com.google.protobuf.ServiceOptions, ?> builder) {
    super(builder);
    this.unknownFields = builder.getUnknownFields();
  }
  private ServiceOptions(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

  private static final ServiceOptions defaultInstance;
  public static ServiceOptions getDefaultInstance() {
    return defaultInstance;
  }

  public ServiceOptions getDefaultInstanceForType() {
    return defaultInstance;
  }

  private final com.google.protobuf.UnknownFieldSet unknownFields;
  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
    return this.unknownFields;
  }
  private ServiceOptions(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    initFields();
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownField(input, unknownFields,
                                   extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 7994: {
            if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
              uninterpretedOption_ = new java.util.ArrayList<com.google.protobuf.UninterpretedOption>();
              mutable_bitField0_ |= 0x00000001;
            }
            uninterpretedOption_.add(input.readMessage(com.google.protobuf.UninterpretedOption.PARSER, extensionRegistry));
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e.getMessage()).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
        uninterpretedOption_ = java.util.Collections.unmodifiableList(uninterpretedOption_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.google.protobuf.DescriptorProtos.internal_static_google_protobuf_ServiceOptions_descriptor;
  }

  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.google.protobuf.DescriptorProtos.internal_static_google_protobuf_ServiceOptions_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.google.protobuf.ServiceOptions.class, com.google.protobuf.ServiceOptions.Builder.class);
  }

  public static com.google.protobuf.Parser<ServiceOptions> PARSER =
      new com.google.protobuf.AbstractParser<ServiceOptions>() {
    public ServiceOptions parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new ServiceOptions(input, extensionRegistry);
    }
  };

  @java.lang.Override
  public com.google.protobuf.Parser<ServiceOptions> getParserForType() {
    return PARSER;
  }

  // repeated .google.protobuf.UninterpretedOption uninterpreted_option = 999;
  public static final int UNINTERPRETED_OPTION_FIELD_NUMBER = 999;
  private java.util.List<com.google.protobuf.UninterpretedOption> uninterpretedOption_;
  /**
   * <code>repeated .google.protobuf.UninterpretedOption uninterpreted_option = 999;</code>
   *
   * <pre>
   * The parser stores options it doesn't recognize here. See above.
   * </pre>
   */
  public java.util.List<com.google.protobuf.UninterpretedOption> getUninterpretedOptionList() {
    return uninterpretedOption_;
  }
  /**
   * <code>repeated .google.protobuf.UninterpretedOption uninterpreted_option = 999;</code>
   *
   * <pre>
   * The parser stores options it doesn't recognize here. See above.
   * </pre>
   */
  public java.util.List<? extends com.google.protobuf.UninterpretedOptionOrBuilder> 
      getUninterpretedOptionOrBuilderList() {
    return uninterpretedOption_;
  }
  /**
   * <code>repeated .google.protobuf.UninterpretedOption uninterpreted_option = 999;</code>
   *
   * <pre>
   * The parser stores options it doesn't recognize here. See above.
   * </pre>
   */
  public int getUninterpretedOptionCount() {
    return uninterpretedOption_.size();
  }
  /**
   * <code>repeated .google.protobuf.UninterpretedOption uninterpreted_option = 999;</code>
   *
   * <pre>
   * The parser stores options it doesn't recognize here. See above.
   * </pre>
   */
  public com.google.protobuf.UninterpretedOption getUninterpretedOption(int index) {
    return uninterpretedOption_.get(index);
  }
  /**
   * <code>repeated .google.protobuf.UninterpretedOption uninterpreted_option = 999;</code>
   *
   * <pre>
   * The parser stores options it doesn't recognize here. See above.
   * </pre>
   */
  public com.google.protobuf.UninterpretedOptionOrBuilder getUninterpretedOptionOrBuilder(
      int index) {
    return uninterpretedOption_.get(index);
  }

  private void initFields() {
    uninterpretedOption_ = java.util.Collections.emptyList();
  }
  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized != -1) return isInitialized == 1;

    for (int i = 0; i < getUninterpretedOptionCount(); i++) {
      if (!getUninterpretedOption(i).isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
    }
    if (!extensionsAreInitialized()) {
      memoizedIsInitialized = 0;
      return false;
    }
    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    getSerializedSize();
    com.google.protobuf.GeneratedMessage
      .ExtendableMessage<com.google.protobuf.ServiceOptions>.ExtensionWriter extensionWriter =
        newExtensionWriter();
    for (int i = 0; i < uninterpretedOption_.size(); i++) {
      output.writeMessage(999, uninterpretedOption_.get(i));
    }
    extensionWriter.writeUntil(536870912, output);
    getUnknownFields().writeTo(output);
  }

  private int memoizedSerializedSize = -1;
  public int getSerializedSize() {
    int size = memoizedSerializedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < uninterpretedOption_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(999, uninterpretedOption_.get(i));
    }
    size += extensionsSerializedSize();
    size += getUnknownFields().getSerializedSize();
    memoizedSerializedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  protected java.lang.Object writeReplace()
      throws java.io.ObjectStreamException {
    return super.writeReplace();
  }

  public static com.google.protobuf.ServiceOptions parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.google.protobuf.ServiceOptions parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.google.protobuf.ServiceOptions parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.google.protobuf.ServiceOptions parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.google.protobuf.ServiceOptions parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return PARSER.parseFrom(input);
  }
  public static com.google.protobuf.ServiceOptions parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseFrom(input, extensionRegistry);
  }
  public static com.google.protobuf.ServiceOptions parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return PARSER.parseDelimitedFrom(input);
  }
  public static com.google.protobuf.ServiceOptions parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseDelimitedFrom(input, extensionRegistry);
  }
  public static com.google.protobuf.ServiceOptions parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return PARSER.parseFrom(input);
  }
  public static com.google.protobuf.ServiceOptions parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseFrom(input, extensionRegistry);
  }

  public static Builder newBuilder() { return Builder.create(); }
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder(com.google.protobuf.ServiceOptions prototype) {
    return newBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() { return newBuilder(this); }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code google.protobuf.ServiceOptions}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.ExtendableBuilder<
        com.google.protobuf.ServiceOptions, Builder> implements com.google.protobuf.ServiceOptionsOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.google.protobuf.DescriptorProtos.internal_static_google_protobuf_ServiceOptions_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.google.protobuf.DescriptorProtos.internal_static_google_protobuf_ServiceOptions_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.google.protobuf.ServiceOptions.class, com.google.protobuf.ServiceOptions.Builder.class);
    }

    // Construct using com.google.protobuf.ServiceOptions.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        getUninterpretedOptionFieldBuilder();
      }
    }
    private static Builder create() {
      return new Builder();
    }

    public Builder clear() {
      super.clear();
      if (uninterpretedOptionBuilder_ == null) {
        uninterpretedOption_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        uninterpretedOptionBuilder_.clear();
      }
      return this;
    }

    public Builder clone() {
      return create().mergeFrom(buildPartial());
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.google.protobuf.DescriptorProtos.internal_static_google_protobuf_ServiceOptions_descriptor;
    }

    public com.google.protobuf.ServiceOptions getDefaultInstanceForType() {
      return com.google.protobuf.ServiceOptions.getDefaultInstance();
    }

    public com.google.protobuf.ServiceOptions build() {
      com.google.protobuf.ServiceOptions result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.google.protobuf.ServiceOptions buildPartial() {
      com.google.protobuf.ServiceOptions result = new com.google.protobuf.ServiceOptions(this);
      int from_bitField0_ = bitField0_;
      if (uninterpretedOptionBuilder_ == null) {
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          uninterpretedOption_ = java.util.Collections.unmodifiableList(uninterpretedOption_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.uninterpretedOption_ = uninterpretedOption_;
      } else {
        result.uninterpretedOption_ = uninterpretedOptionBuilder_.build();
      }
      onBuilt();
      return result;
    }

    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.google.protobuf.ServiceOptions) {
        return mergeFrom((com.google.protobuf.ServiceOptions)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.google.protobuf.ServiceOptions other) {
      if (other == com.google.protobuf.ServiceOptions.getDefaultInstance()) return this;
      if (uninterpretedOptionBuilder_ == null) {
        if (!other.uninterpretedOption_.isEmpty()) {
          if (uninterpretedOption_.isEmpty()) {
            uninterpretedOption_ = other.uninterpretedOption_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureUninterpretedOptionIsMutable();
            uninterpretedOption_.addAll(other.uninterpretedOption_);
          }
          onChanged();
        }
      } else {
        if (!other.uninterpretedOption_.isEmpty()) {
          if (uninterpretedOptionBuilder_.isEmpty()) {
            uninterpretedOptionBuilder_.dispose();
            uninterpretedOptionBuilder_ = null;
            uninterpretedOption_ = other.uninterpretedOption_;
            bitField0_ = (bitField0_ & ~0x00000001);
            uninterpretedOptionBuilder_ = 
              com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                 getUninterpretedOptionFieldBuilder() : null;
          } else {
            uninterpretedOptionBuilder_.addAllMessages(other.uninterpretedOption_);
          }
        }
      }
      this.mergeExtensionFields(other);
      this.mergeUnknownFields(other.getUnknownFields());
      return this;
    }

    public final boolean isInitialized() {
      for (int i = 0; i < getUninterpretedOptionCount(); i++) {
        if (!getUninterpretedOption(i).isInitialized()) {
          
          return false;
        }
      }
      if (!extensionsAreInitialized()) {
        
        return false;
      }
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.google.protobuf.ServiceOptions parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.google.protobuf.ServiceOptions) e.getUnfinishedMessage();
        throw e;
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    // repeated .google.protobuf.UninterpretedOption uninterpreted_option = 999;
    private java.util.List<com.google.protobuf.UninterpretedOption> uninterpretedOption_ =
      java.util.Collections.emptyList();
    private void ensureUninterpretedOptionIsMutable() {
      if (!((bitField0_ & 0x00000001) == 0x00000001)) {
        uninterpretedOption_ = new java.util.ArrayList<com.google.protobuf.UninterpretedOption>(uninterpretedOption_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilder<
        com.google.protobuf.UninterpretedOption, com.google.protobuf.UninterpretedOption.Builder, com.google.protobuf.UninterpretedOptionOrBuilder> uninterpretedOptionBuilder_;

    /**
     * <code>repeated .google.protobuf.UninterpretedOption uninterpreted_option = 999;</code>
     *
     * <pre>
     * The parser stores options it doesn't recognize here. See above.
     * </pre>
     */
    public java.util.List<com.google.protobuf.UninterpretedOption> getUninterpretedOptionList() {
      if (uninterpretedOptionBuilder_ == null) {
        return java.util.Collections.unmodifiableList(uninterpretedOption_);
      } else {
        return uninterpretedOptionBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .google.protobuf.UninterpretedOption uninterpreted_option = 999;</code>
     *
     * <pre>
     * The parser stores options it doesn't recognize here. See above.
     * </pre>
     */
    public int getUninterpretedOptionCount() {
      if (uninterpretedOptionBuilder_ == null) {
        return uninterpretedOption_.size();
      } else {
        return uninterpretedOptionBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .google.protobuf.UninterpretedOption uninterpreted_option = 999;</code>
     *
     * <pre>
     * The parser stores options it doesn't recognize here. See above.
     * </pre>
     */
    public com.google.protobuf.UninterpretedOption getUninterpretedOption(int index) {
      if (uninterpretedOptionBuilder_ == null) {
        return uninterpretedOption_.get(index);
      } else {
        return uninterpretedOptionBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .google.protobuf.UninterpretedOption uninterpreted_option = 999;</code>
     *
     * <pre>
     * The parser stores options it doesn't recognize here. See above.
     * </pre>
     */
    public Builder setUninterpretedOption(
        int index, com.google.protobuf.UninterpretedOption value) {
      if (uninterpretedOptionBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureUninterpretedOptionIsMutable();
        uninterpretedOption_.set(index, value);
        onChanged();
      } else {
        uninterpretedOptionBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .google.protobuf.UninterpretedOption uninterpreted_option = 999;</code>
     *
     * <pre>
     * The parser stores options it doesn't recognize here. See above.
     * </pre>
     */
    public Builder setUninterpretedOption(
        int index, com.google.protobuf.UninterpretedOption.Builder builderForValue) {
      if (uninterpretedOptionBuilder_ == null) {
        ensureUninterpretedOptionIsMutable();
        uninterpretedOption_.set(index, builderForValue.build());
        onChanged();
      } else {
        uninterpretedOptionBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .google.protobuf.UninterpretedOption uninterpreted_option = 999;</code>
     *
     * <pre>
     * The parser stores options it doesn't recognize here. See above.
     * </pre>
     */
    public Builder addUninterpretedOption(com.google.protobuf.UninterpretedOption value) {
      if (uninterpretedOptionBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureUninterpretedOptionIsMutable();
        uninterpretedOption_.add(value);
        onChanged();
      } else {
        uninterpretedOptionBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .google.protobuf.UninterpretedOption uninterpreted_option = 999;</code>
     *
     * <pre>
     * The parser stores options it doesn't recognize here. See above.
     * </pre>
     */
    public Builder addUninterpretedOption(
        int index, com.google.protobuf.UninterpretedOption value) {
      if (uninterpretedOptionBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureUninterpretedOptionIsMutable();
        uninterpretedOption_.add(index, value);
        onChanged();
      } else {
        uninterpretedOptionBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .google.protobuf.UninterpretedOption uninterpreted_option = 999;</code>
     *
     * <pre>
     * The parser stores options it doesn't recognize here. See above.
     * </pre>
     */
    public Builder addUninterpretedOption(
        com.google.protobuf.UninterpretedOption.Builder builderForValue) {
      if (uninterpretedOptionBuilder_ == null) {
        ensureUninterpretedOptionIsMutable();
        uninterpretedOption_.add(builderForValue.build());
        onChanged();
      } else {
        uninterpretedOptionBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .google.protobuf.UninterpretedOption uninterpreted_option = 999;</code>
     *
     * <pre>
     * The parser stores options it doesn't recognize here. See above.
     * </pre>
     */
    public Builder addUninterpretedOption(
        int index, com.google.protobuf.UninterpretedOption.Builder builderForValue) {
      if (uninterpretedOptionBuilder_ == null) {
        ensureUninterpretedOptionIsMutable();
        uninterpretedOption_.add(index, builderForValue.build());
        onChanged();
      } else {
        uninterpretedOptionBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .google.protobuf.UninterpretedOption uninterpreted_option = 999;</code>
     *
     * <pre>
     * The parser stores options it doesn't recognize here. See above.
     * </pre>
     */
    public Builder addAllUninterpretedOption(
        java.lang.Iterable<? extends com.google.protobuf.UninterpretedOption> values) {
      if (uninterpretedOptionBuilder_ == null) {
        ensureUninterpretedOptionIsMutable();
        super.addAll(values, uninterpretedOption_);
        onChanged();
      } else {
        uninterpretedOptionBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .google.protobuf.UninterpretedOption uninterpreted_option = 999;</code>
     *
     * <pre>
     * The parser stores options it doesn't recognize here. See above.
     * </pre>
     */
    public Builder clearUninterpretedOption() {
      if (uninterpretedOptionBuilder_ == null) {
        uninterpretedOption_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        uninterpretedOptionBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .google.protobuf.UninterpretedOption uninterpreted_option = 999;</code>
     *
     * <pre>
     * The parser stores options it doesn't recognize here. See above.
     * </pre>
     */
    public Builder removeUninterpretedOption(int index) {
      if (uninterpretedOptionBuilder_ == null) {
        ensureUninterpretedOptionIsMutable();
        uninterpretedOption_.remove(index);
        onChanged();
      } else {
        uninterpretedOptionBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .google.protobuf.UninterpretedOption uninterpreted_option = 999;</code>
     *
     * <pre>
     * The parser stores options it doesn't recognize here. See above.
     * </pre>
     */
    public com.google.protobuf.UninterpretedOption.Builder getUninterpretedOptionBuilder(
        int index) {
      return getUninterpretedOptionFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .google.protobuf.UninterpretedOption uninterpreted_option = 999;</code>
     *
     * <pre>
     * The parser stores options it doesn't recognize here. See above.
     * </pre>
     */
    public com.google.protobuf.UninterpretedOptionOrBuilder getUninterpretedOptionOrBuilder(
        int index) {
      if (uninterpretedOptionBuilder_ == null) {
        return uninterpretedOption_.get(index);  } else {
        return uninterpretedOptionBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .google.protobuf.UninterpretedOption uninterpreted_option = 999;</code>
     *
     * <pre>
     * The parser stores options it doesn't recognize here. See above.
     * </pre>
     */
    public java.util.List<? extends com.google.protobuf.UninterpretedOptionOrBuilder> 
         getUninterpretedOptionOrBuilderList() {
      if (uninterpretedOptionBuilder_ != null) {
        return uninterpretedOptionBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(uninterpretedOption_);
      }
    }
    /**
     * <code>repeated .google.protobuf.UninterpretedOption uninterpreted_option = 999;</code>
     *
     * <pre>
     * The parser stores options it doesn't recognize here. See above.
     * </pre>
     */
    public com.google.protobuf.UninterpretedOption.Builder addUninterpretedOptionBuilder() {
      return getUninterpretedOptionFieldBuilder().addBuilder(
          com.google.protobuf.UninterpretedOption.getDefaultInstance());
    }
    /**
     * <code>repeated .google.protobuf.UninterpretedOption uninterpreted_option = 999;</code>
     *
     * <pre>
     * The parser stores options it doesn't recognize here. See above.
     * </pre>
     */
    public com.google.protobuf.UninterpretedOption.Builder addUninterpretedOptionBuilder(
        int index) {
      return getUninterpretedOptionFieldBuilder().addBuilder(
          index, com.google.protobuf.UninterpretedOption.getDefaultInstance());
    }
    /**
     * <code>repeated .google.protobuf.UninterpretedOption uninterpreted_option = 999;</code>
     *
     * <pre>
     * The parser stores options it doesn't recognize here. See above.
     * </pre>
     */
    public java.util.List<com.google.protobuf.UninterpretedOption.Builder> 
         getUninterpretedOptionBuilderList() {
      return getUninterpretedOptionFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilder<
        com.google.protobuf.UninterpretedOption, com.google.protobuf.UninterpretedOption.Builder, com.google.protobuf.UninterpretedOptionOrBuilder> 
        getUninterpretedOptionFieldBuilder() {
      if (uninterpretedOptionBuilder_ == null) {
        uninterpretedOptionBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
            com.google.protobuf.UninterpretedOption, com.google.protobuf.UninterpretedOption.Builder, com.google.protobuf.UninterpretedOptionOrBuilder>(
                uninterpretedOption_,
                ((bitField0_ & 0x00000001) == 0x00000001),
                getParentForChildren(),
                isClean());
        uninterpretedOption_ = null;
      }
      return uninterpretedOptionBuilder_;
    }

    // @@protoc_insertion_point(builder_scope:google.protobuf.ServiceOptions)
  }

  static {
    defaultInstance = new ServiceOptions(true);
    defaultInstance.initFields();
  }

  // @@protoc_insertion_point(class_scope:google.protobuf.ServiceOptions)
}

