// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: descriptor.proto

package com.google.protobuf;

/**
 * Protobuf type {@code google.protobuf.UninterpretedOption}
 *
 * <pre>
 * A message representing a option the parser does not recognize. This only
 * appears in options protos created by the compiler::Parser class.
 * DescriptorPool resolves these when building Descriptor objects. Therefore,
 * options protos in descriptor objects (e.g. returned by Descriptor::options(),
 * or produced by Descriptor::CopyTo()) will never have UninterpretedOptions
 * in them.
 * </pre>
 */
public  final class UninterpretedOption extends
    com.google.protobuf.GeneratedMessage
    implements UninterpretedOptionOrBuilder {
  // Use UninterpretedOption.newBuilder() to construct.
  private UninterpretedOption(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
    this.unknownFields = builder.getUnknownFields();
  }
  private UninterpretedOption(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

  private static final UninterpretedOption defaultInstance;
  public static UninterpretedOption getDefaultInstance() {
    return defaultInstance;
  }

  public UninterpretedOption getDefaultInstanceForType() {
    return defaultInstance;
  }

  private final com.google.protobuf.UnknownFieldSet unknownFields;
  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
    return this.unknownFields;
  }
  private UninterpretedOption(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    initFields();
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownField(input, unknownFields,
                                   extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 18: {
            if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
              name_ = new java.util.ArrayList<com.google.protobuf.UninterpretedOption.NamePart>();
              mutable_bitField0_ |= 0x00000001;
            }
            name_.add(input.readMessage(com.google.protobuf.UninterpretedOption.NamePart.PARSER, extensionRegistry));
            break;
          }
          case 26: {
            bitField0_ |= 0x00000001;
            identifierValue_ = input.readBytes();
            break;
          }
          case 32: {
            bitField0_ |= 0x00000002;
            positiveIntValue_ = input.readUInt64();
            break;
          }
          case 40: {
            bitField0_ |= 0x00000004;
            negativeIntValue_ = input.readInt64();
            break;
          }
          case 49: {
            bitField0_ |= 0x00000008;
            doubleValue_ = input.readDouble();
            break;
          }
          case 58: {
            bitField0_ |= 0x00000010;
            stringValue_ = input.readBytes();
            break;
          }
          case 66: {
            bitField0_ |= 0x00000020;
            aggregateValue_ = input.readBytes();
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e.getMessage()).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
        name_ = java.util.Collections.unmodifiableList(name_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.google.protobuf.DescriptorProtos.internal_static_google_protobuf_UninterpretedOption_descriptor;
  }

  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.google.protobuf.DescriptorProtos.internal_static_google_protobuf_UninterpretedOption_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.google.protobuf.UninterpretedOption.class, com.google.protobuf.UninterpretedOption.Builder.class);
  }

  public static com.google.protobuf.Parser<UninterpretedOption> PARSER =
      new com.google.protobuf.AbstractParser<UninterpretedOption>() {
    public UninterpretedOption parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new UninterpretedOption(input, extensionRegistry);
    }
  };

  @java.lang.Override
  public com.google.protobuf.Parser<UninterpretedOption> getParserForType() {
    return PARSER;
  }

  public interface NamePartOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required string name_part = 1;
    /**
     * <code>required string name_part = 1;</code>
     */
    boolean hasNamePart();
    /**
     * <code>required string name_part = 1;</code>
     */
    java.lang.String getNamePart();
    /**
     * <code>required string name_part = 1;</code>
     */
    com.google.protobuf.ByteString
        getNamePartBytes();

    // required bool is_extension = 2;
    /**
     * <code>required bool is_extension = 2;</code>
     */
    boolean hasIsExtension();
    /**
     * <code>required bool is_extension = 2;</code>
     */
    boolean getIsExtension();
  }
  /**
   * Protobuf type {@code google.protobuf.UninterpretedOption.NamePart}
   *
   * <pre>
   * The name of the uninterpreted option.  Each string represents a segment in
   * a dot-separated name.  is_extension is true iff a segment represents an
   * extension (denoted with parentheses in options specs in .proto files).
   * E.g.,{ ["foo", false], ["bar.baz", true], ["qux", false] } represents
   * "foo.(bar.baz).qux".
   * </pre>
   */
  public static final class NamePart extends
      com.google.protobuf.GeneratedMessage
      implements NamePartOrBuilder {
    // Use NamePart.newBuilder() to construct.
    private NamePart(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private NamePart(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final NamePart defaultInstance;
    public static NamePart getDefaultInstance() {
      return defaultInstance;
    }

    public NamePart getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private NamePart(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              namePart_ = input.readBytes();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              isExtension_ = input.readBool();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.google.protobuf.DescriptorProtos.internal_static_google_protobuf_UninterpretedOption_NamePart_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.google.protobuf.DescriptorProtos.internal_static_google_protobuf_UninterpretedOption_NamePart_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.google.protobuf.UninterpretedOption.NamePart.class, com.google.protobuf.UninterpretedOption.NamePart.Builder.class);
    }

    public static com.google.protobuf.Parser<NamePart> PARSER =
        new com.google.protobuf.AbstractParser<NamePart>() {
      public NamePart parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new NamePart(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<NamePart> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required string name_part = 1;
    public static final int NAME_PART_FIELD_NUMBER = 1;
    private java.lang.Object namePart_;
    /**
     * <code>required string name_part = 1;</code>
     */
    public boolean hasNamePart() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string name_part = 1;</code>
     */
    public java.lang.String getNamePart() {
      java.lang.Object ref = namePart_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          namePart_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string name_part = 1;</code>
     */
    public com.google.protobuf.ByteString
        getNamePartBytes() {
      java.lang.Object ref = namePart_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        namePart_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required bool is_extension = 2;
    public static final int IS_EXTENSION_FIELD_NUMBER = 2;
    private boolean isExtension_;
    /**
     * <code>required bool is_extension = 2;</code>
     */
    public boolean hasIsExtension() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required bool is_extension = 2;</code>
     */
    public boolean getIsExtension() {
      return isExtension_;
    }

    private void initFields() {
      namePart_ = "";
      isExtension_ = false;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasNamePart()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasIsExtension()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getNamePartBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBool(2, isExtension_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getNamePartBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(2, isExtension_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.google.protobuf.UninterpretedOption.NamePart parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.google.protobuf.UninterpretedOption.NamePart parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.google.protobuf.UninterpretedOption.NamePart parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.google.protobuf.UninterpretedOption.NamePart parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.google.protobuf.UninterpretedOption.NamePart parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.google.protobuf.UninterpretedOption.NamePart parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.google.protobuf.UninterpretedOption.NamePart parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.google.protobuf.UninterpretedOption.NamePart parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.google.protobuf.UninterpretedOption.NamePart parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.google.protobuf.UninterpretedOption.NamePart parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.google.protobuf.UninterpretedOption.NamePart prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code google.protobuf.UninterpretedOption.NamePart}
     *
     * <pre>
     * The name of the uninterpreted option.  Each string represents a segment in
     * a dot-separated name.  is_extension is true iff a segment represents an
     * extension (denoted with parentheses in options specs in .proto files).
     * E.g.,{ ["foo", false], ["bar.baz", true], ["qux", false] } represents
     * "foo.(bar.baz).qux".
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.google.protobuf.UninterpretedOption.NamePartOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.google.protobuf.DescriptorProtos.internal_static_google_protobuf_UninterpretedOption_NamePart_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.google.protobuf.DescriptorProtos.internal_static_google_protobuf_UninterpretedOption_NamePart_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.google.protobuf.UninterpretedOption.NamePart.class, com.google.protobuf.UninterpretedOption.NamePart.Builder.class);
      }

      // Construct using com.google.protobuf.UninterpretedOption.NamePart.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        namePart_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        isExtension_ = false;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.google.protobuf.DescriptorProtos.internal_static_google_protobuf_UninterpretedOption_NamePart_descriptor;
      }

      public com.google.protobuf.UninterpretedOption.NamePart getDefaultInstanceForType() {
        return com.google.protobuf.UninterpretedOption.NamePart.getDefaultInstance();
      }

      public com.google.protobuf.UninterpretedOption.NamePart build() {
        com.google.protobuf.UninterpretedOption.NamePart result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.google.protobuf.UninterpretedOption.NamePart buildPartial() {
        com.google.protobuf.UninterpretedOption.NamePart result = new com.google.protobuf.UninterpretedOption.NamePart(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.namePart_ = namePart_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.isExtension_ = isExtension_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.google.protobuf.UninterpretedOption.NamePart) {
          return mergeFrom((com.google.protobuf.UninterpretedOption.NamePart)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.google.protobuf.UninterpretedOption.NamePart other) {
        if (other == com.google.protobuf.UninterpretedOption.NamePart.getDefaultInstance()) return this;
        if (other.hasNamePart()) {
          bitField0_ |= 0x00000001;
          namePart_ = other.namePart_;
          onChanged();
        }
        if (other.hasIsExtension()) {
          setIsExtension(other.getIsExtension());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasNamePart()) {
          
          return false;
        }
        if (!hasIsExtension()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UninterpretedOption.NamePart parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.google.protobuf.UninterpretedOption.NamePart) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required string name_part = 1;
      private java.lang.Object namePart_ = "";
      /**
       * <code>required string name_part = 1;</code>
       */
      public boolean hasNamePart() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string name_part = 1;</code>
       */
      public java.lang.String getNamePart() {
        java.lang.Object ref = namePart_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          namePart_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string name_part = 1;</code>
       */
      public com.google.protobuf.ByteString
          getNamePartBytes() {
        java.lang.Object ref = namePart_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          namePart_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string name_part = 1;</code>
       */
      public Builder setNamePart(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        namePart_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string name_part = 1;</code>
       */
      public Builder clearNamePart() {
        bitField0_ = (bitField0_ & ~0x00000001);
        namePart_ = getDefaultInstance().getNamePart();
        onChanged();
        return this;
      }
      /**
       * <code>required string name_part = 1;</code>
       */
      public Builder setNamePartBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        namePart_ = value;
        onChanged();
        return this;
      }

      // required bool is_extension = 2;
      private boolean isExtension_ ;
      /**
       * <code>required bool is_extension = 2;</code>
       */
      public boolean hasIsExtension() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required bool is_extension = 2;</code>
       */
      public boolean getIsExtension() {
        return isExtension_;
      }
      /**
       * <code>required bool is_extension = 2;</code>
       */
      public Builder setIsExtension(boolean value) {
        bitField0_ |= 0x00000002;
        isExtension_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bool is_extension = 2;</code>
       */
      public Builder clearIsExtension() {
        bitField0_ = (bitField0_ & ~0x00000002);
        isExtension_ = false;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:google.protobuf.UninterpretedOption.NamePart)
    }

    static {
      defaultInstance = new NamePart(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:google.protobuf.UninterpretedOption.NamePart)
  }

  private int bitField0_;
  // repeated .google.protobuf.UninterpretedOption.NamePart name = 2;
  public static final int NAME_FIELD_NUMBER = 2;
  private java.util.List<com.google.protobuf.UninterpretedOption.NamePart> name_;
  /**
   * <code>repeated .google.protobuf.UninterpretedOption.NamePart name = 2;</code>
   */
  public java.util.List<com.google.protobuf.UninterpretedOption.NamePart> getNameList() {
    return name_;
  }
  /**
   * <code>repeated .google.protobuf.UninterpretedOption.NamePart name = 2;</code>
   */
  public java.util.List<? extends com.google.protobuf.UninterpretedOption.NamePartOrBuilder> 
      getNameOrBuilderList() {
    return name_;
  }
  /**
   * <code>repeated .google.protobuf.UninterpretedOption.NamePart name = 2;</code>
   */
  public int getNameCount() {
    return name_.size();
  }
  /**
   * <code>repeated .google.protobuf.UninterpretedOption.NamePart name = 2;</code>
   */
  public com.google.protobuf.UninterpretedOption.NamePart getName(int index) {
    return name_.get(index);
  }
  /**
   * <code>repeated .google.protobuf.UninterpretedOption.NamePart name = 2;</code>
   */
  public com.google.protobuf.UninterpretedOption.NamePartOrBuilder getNameOrBuilder(
      int index) {
    return name_.get(index);
  }

  // optional string identifier_value = 3;
  public static final int IDENTIFIER_VALUE_FIELD_NUMBER = 3;
  private java.lang.Object identifierValue_;
  /**
   * <code>optional string identifier_value = 3;</code>
   *
   * <pre>
   * The value of the uninterpreted option, in whatever type the tokenizer
   * identified it as during parsing. Exactly one of these should be set.
   * </pre>
   */
  public boolean hasIdentifierValue() {
    return ((bitField0_ & 0x00000001) == 0x00000001);
  }
  /**
   * <code>optional string identifier_value = 3;</code>
   *
   * <pre>
   * The value of the uninterpreted option, in whatever type the tokenizer
   * identified it as during parsing. Exactly one of these should be set.
   * </pre>
   */
  public java.lang.String getIdentifierValue() {
    java.lang.Object ref = identifierValue_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        identifierValue_ = s;
      }
      return s;
    }
  }
  /**
   * <code>optional string identifier_value = 3;</code>
   *
   * <pre>
   * The value of the uninterpreted option, in whatever type the tokenizer
   * identified it as during parsing. Exactly one of these should be set.
   * </pre>
   */
  public com.google.protobuf.ByteString
      getIdentifierValueBytes() {
    java.lang.Object ref = identifierValue_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      identifierValue_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  // optional uint64 positive_int_value = 4;
  public static final int POSITIVE_INT_VALUE_FIELD_NUMBER = 4;
  private long positiveIntValue_;
  /**
   * <code>optional uint64 positive_int_value = 4;</code>
   */
  public boolean hasPositiveIntValue() {
    return ((bitField0_ & 0x00000002) == 0x00000002);
  }
  /**
   * <code>optional uint64 positive_int_value = 4;</code>
   */
  public long getPositiveIntValue() {
    return positiveIntValue_;
  }

  // optional int64 negative_int_value = 5;
  public static final int NEGATIVE_INT_VALUE_FIELD_NUMBER = 5;
  private long negativeIntValue_;
  /**
   * <code>optional int64 negative_int_value = 5;</code>
   */
  public boolean hasNegativeIntValue() {
    return ((bitField0_ & 0x00000004) == 0x00000004);
  }
  /**
   * <code>optional int64 negative_int_value = 5;</code>
   */
  public long getNegativeIntValue() {
    return negativeIntValue_;
  }

  // optional double double_value = 6;
  public static final int DOUBLE_VALUE_FIELD_NUMBER = 6;
  private double doubleValue_;
  /**
   * <code>optional double double_value = 6;</code>
   */
  public boolean hasDoubleValue() {
    return ((bitField0_ & 0x00000008) == 0x00000008);
  }
  /**
   * <code>optional double double_value = 6;</code>
   */
  public double getDoubleValue() {
    return doubleValue_;
  }

  // optional bytes string_value = 7;
  public static final int STRING_VALUE_FIELD_NUMBER = 7;
  private com.google.protobuf.ByteString stringValue_;
  /**
   * <code>optional bytes string_value = 7;</code>
   */
  public boolean hasStringValue() {
    return ((bitField0_ & 0x00000010) == 0x00000010);
  }
  /**
   * <code>optional bytes string_value = 7;</code>
   */
  public com.google.protobuf.ByteString getStringValue() {
    return stringValue_;
  }

  // optional string aggregate_value = 8;
  public static final int AGGREGATE_VALUE_FIELD_NUMBER = 8;
  private java.lang.Object aggregateValue_;
  /**
   * <code>optional string aggregate_value = 8;</code>
   */
  public boolean hasAggregateValue() {
    return ((bitField0_ & 0x00000020) == 0x00000020);
  }
  /**
   * <code>optional string aggregate_value = 8;</code>
   */
  public java.lang.String getAggregateValue() {
    java.lang.Object ref = aggregateValue_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        aggregateValue_ = s;
      }
      return s;
    }
  }
  /**
   * <code>optional string aggregate_value = 8;</code>
   */
  public com.google.protobuf.ByteString
      getAggregateValueBytes() {
    java.lang.Object ref = aggregateValue_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      aggregateValue_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private void initFields() {
    name_ = java.util.Collections.emptyList();
    identifierValue_ = "";
    positiveIntValue_ = 0L;
    negativeIntValue_ = 0L;
    doubleValue_ = 0D;
    stringValue_ = com.google.protobuf.ByteString.EMPTY;
    aggregateValue_ = "";
  }
  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized != -1) return isInitialized == 1;

    for (int i = 0; i < getNameCount(); i++) {
      if (!getName(i).isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
    }
    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    getSerializedSize();
    for (int i = 0; i < name_.size(); i++) {
      output.writeMessage(2, name_.get(i));
    }
    if (((bitField0_ & 0x00000001) == 0x00000001)) {
      output.writeBytes(3, getIdentifierValueBytes());
    }
    if (((bitField0_ & 0x00000002) == 0x00000002)) {
      output.writeUInt64(4, positiveIntValue_);
    }
    if (((bitField0_ & 0x00000004) == 0x00000004)) {
      output.writeInt64(5, negativeIntValue_);
    }
    if (((bitField0_ & 0x00000008) == 0x00000008)) {
      output.writeDouble(6, doubleValue_);
    }
    if (((bitField0_ & 0x00000010) == 0x00000010)) {
      output.writeBytes(7, stringValue_);
    }
    if (((bitField0_ & 0x00000020) == 0x00000020)) {
      output.writeBytes(8, getAggregateValueBytes());
    }
    getUnknownFields().writeTo(output);
  }

  private int memoizedSerializedSize = -1;
  public int getSerializedSize() {
    int size = memoizedSerializedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < name_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, name_.get(i));
    }
    if (((bitField0_ & 0x00000001) == 0x00000001)) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(3, getIdentifierValueBytes());
    }
    if (((bitField0_ & 0x00000002) == 0x00000002)) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(4, positiveIntValue_);
    }
    if (((bitField0_ & 0x00000004) == 0x00000004)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(5, negativeIntValue_);
    }
    if (((bitField0_ & 0x00000008) == 0x00000008)) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(6, doubleValue_);
    }
    if (((bitField0_ & 0x00000010) == 0x00000010)) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(7, stringValue_);
    }
    if (((bitField0_ & 0x00000020) == 0x00000020)) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(8, getAggregateValueBytes());
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSerializedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  protected java.lang.Object writeReplace()
      throws java.io.ObjectStreamException {
    return super.writeReplace();
  }

  public static com.google.protobuf.UninterpretedOption parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.google.protobuf.UninterpretedOption parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.google.protobuf.UninterpretedOption parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.google.protobuf.UninterpretedOption parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.google.protobuf.UninterpretedOption parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return PARSER.parseFrom(input);
  }
  public static com.google.protobuf.UninterpretedOption parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseFrom(input, extensionRegistry);
  }
  public static com.google.protobuf.UninterpretedOption parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return PARSER.parseDelimitedFrom(input);
  }
  public static com.google.protobuf.UninterpretedOption parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseDelimitedFrom(input, extensionRegistry);
  }
  public static com.google.protobuf.UninterpretedOption parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return PARSER.parseFrom(input);
  }
  public static com.google.protobuf.UninterpretedOption parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseFrom(input, extensionRegistry);
  }

  public static Builder newBuilder() { return Builder.create(); }
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder(com.google.protobuf.UninterpretedOption prototype) {
    return newBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() { return newBuilder(this); }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code google.protobuf.UninterpretedOption}
   *
   * <pre>
   * A message representing a option the parser does not recognize. This only
   * appears in options protos created by the compiler::Parser class.
   * DescriptorPool resolves these when building Descriptor objects. Therefore,
   * options protos in descriptor objects (e.g. returned by Descriptor::options(),
   * or produced by Descriptor::CopyTo()) will never have UninterpretedOptions
   * in them.
   * </pre>
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder>
     implements com.google.protobuf.UninterpretedOptionOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.google.protobuf.DescriptorProtos.internal_static_google_protobuf_UninterpretedOption_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.google.protobuf.DescriptorProtos.internal_static_google_protobuf_UninterpretedOption_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.google.protobuf.UninterpretedOption.class, com.google.protobuf.UninterpretedOption.Builder.class);
    }

    // Construct using com.google.protobuf.UninterpretedOption.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        getNameFieldBuilder();
      }
    }
    private static Builder create() {
      return new Builder();
    }

    public Builder clear() {
      super.clear();
      if (nameBuilder_ == null) {
        name_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        nameBuilder_.clear();
      }
      identifierValue_ = "";
      bitField0_ = (bitField0_ & ~0x00000002);
      positiveIntValue_ = 0L;
      bitField0_ = (bitField0_ & ~0x00000004);
      negativeIntValue_ = 0L;
      bitField0_ = (bitField0_ & ~0x00000008);
      doubleValue_ = 0D;
      bitField0_ = (bitField0_ & ~0x00000010);
      stringValue_ = com.google.protobuf.ByteString.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000020);
      aggregateValue_ = "";
      bitField0_ = (bitField0_ & ~0x00000040);
      return this;
    }

    public Builder clone() {
      return create().mergeFrom(buildPartial());
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.google.protobuf.DescriptorProtos.internal_static_google_protobuf_UninterpretedOption_descriptor;
    }

    public com.google.protobuf.UninterpretedOption getDefaultInstanceForType() {
      return com.google.protobuf.UninterpretedOption.getDefaultInstance();
    }

    public com.google.protobuf.UninterpretedOption build() {
      com.google.protobuf.UninterpretedOption result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.google.protobuf.UninterpretedOption buildPartial() {
      com.google.protobuf.UninterpretedOption result = new com.google.protobuf.UninterpretedOption(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (nameBuilder_ == null) {
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          name_ = java.util.Collections.unmodifiableList(name_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.name_ = name_;
      } else {
        result.name_ = nameBuilder_.build();
      }
      if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
        to_bitField0_ |= 0x00000001;
      }
      result.identifierValue_ = identifierValue_;
      if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
        to_bitField0_ |= 0x00000002;
      }
      result.positiveIntValue_ = positiveIntValue_;
      if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
        to_bitField0_ |= 0x00000004;
      }
      result.negativeIntValue_ = negativeIntValue_;
      if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
        to_bitField0_ |= 0x00000008;
      }
      result.doubleValue_ = doubleValue_;
      if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
        to_bitField0_ |= 0x00000010;
      }
      result.stringValue_ = stringValue_;
      if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
        to_bitField0_ |= 0x00000020;
      }
      result.aggregateValue_ = aggregateValue_;
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.google.protobuf.UninterpretedOption) {
        return mergeFrom((com.google.protobuf.UninterpretedOption)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.google.protobuf.UninterpretedOption other) {
      if (other == com.google.protobuf.UninterpretedOption.getDefaultInstance()) return this;
      if (nameBuilder_ == null) {
        if (!other.name_.isEmpty()) {
          if (name_.isEmpty()) {
            name_ = other.name_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureNameIsMutable();
            name_.addAll(other.name_);
          }
          onChanged();
        }
      } else {
        if (!other.name_.isEmpty()) {
          if (nameBuilder_.isEmpty()) {
            nameBuilder_.dispose();
            nameBuilder_ = null;
            name_ = other.name_;
            bitField0_ = (bitField0_ & ~0x00000001);
            nameBuilder_ = 
              com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                 getNameFieldBuilder() : null;
          } else {
            nameBuilder_.addAllMessages(other.name_);
          }
        }
      }
      if (other.hasIdentifierValue()) {
        bitField0_ |= 0x00000002;
        identifierValue_ = other.identifierValue_;
        onChanged();
      }
      if (other.hasPositiveIntValue()) {
        setPositiveIntValue(other.getPositiveIntValue());
      }
      if (other.hasNegativeIntValue()) {
        setNegativeIntValue(other.getNegativeIntValue());
      }
      if (other.hasDoubleValue()) {
        setDoubleValue(other.getDoubleValue());
      }
      if (other.hasStringValue()) {
        setStringValue(other.getStringValue());
      }
      if (other.hasAggregateValue()) {
        bitField0_ |= 0x00000040;
        aggregateValue_ = other.aggregateValue_;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      return this;
    }

    public final boolean isInitialized() {
      for (int i = 0; i < getNameCount(); i++) {
        if (!getName(i).isInitialized()) {
          
          return false;
        }
      }
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.google.protobuf.UninterpretedOption parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.google.protobuf.UninterpretedOption) e.getUnfinishedMessage();
        throw e;
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    // repeated .google.protobuf.UninterpretedOption.NamePart name = 2;
    private java.util.List<com.google.protobuf.UninterpretedOption.NamePart> name_ =
      java.util.Collections.emptyList();
    private void ensureNameIsMutable() {
      if (!((bitField0_ & 0x00000001) == 0x00000001)) {
        name_ = new java.util.ArrayList<com.google.protobuf.UninterpretedOption.NamePart>(name_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilder<
        com.google.protobuf.UninterpretedOption.NamePart, com.google.protobuf.UninterpretedOption.NamePart.Builder, com.google.protobuf.UninterpretedOption.NamePartOrBuilder> nameBuilder_;

    /**
     * <code>repeated .google.protobuf.UninterpretedOption.NamePart name = 2;</code>
     */
    public java.util.List<com.google.protobuf.UninterpretedOption.NamePart> getNameList() {
      if (nameBuilder_ == null) {
        return java.util.Collections.unmodifiableList(name_);
      } else {
        return nameBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .google.protobuf.UninterpretedOption.NamePart name = 2;</code>
     */
    public int getNameCount() {
      if (nameBuilder_ == null) {
        return name_.size();
      } else {
        return nameBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .google.protobuf.UninterpretedOption.NamePart name = 2;</code>
     */
    public com.google.protobuf.UninterpretedOption.NamePart getName(int index) {
      if (nameBuilder_ == null) {
        return name_.get(index);
      } else {
        return nameBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .google.protobuf.UninterpretedOption.NamePart name = 2;</code>
     */
    public Builder setName(
        int index, com.google.protobuf.UninterpretedOption.NamePart value) {
      if (nameBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureNameIsMutable();
        name_.set(index, value);
        onChanged();
      } else {
        nameBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .google.protobuf.UninterpretedOption.NamePart name = 2;</code>
     */
    public Builder setName(
        int index, com.google.protobuf.UninterpretedOption.NamePart.Builder builderForValue) {
      if (nameBuilder_ == null) {
        ensureNameIsMutable();
        name_.set(index, builderForValue.build());
        onChanged();
      } else {
        nameBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .google.protobuf.UninterpretedOption.NamePart name = 2;</code>
     */
    public Builder addName(com.google.protobuf.UninterpretedOption.NamePart value) {
      if (nameBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureNameIsMutable();
        name_.add(value);
        onChanged();
      } else {
        nameBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .google.protobuf.UninterpretedOption.NamePart name = 2;</code>
     */
    public Builder addName(
        int index, com.google.protobuf.UninterpretedOption.NamePart value) {
      if (nameBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureNameIsMutable();
        name_.add(index, value);
        onChanged();
      } else {
        nameBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .google.protobuf.UninterpretedOption.NamePart name = 2;</code>
     */
    public Builder addName(
        com.google.protobuf.UninterpretedOption.NamePart.Builder builderForValue) {
      if (nameBuilder_ == null) {
        ensureNameIsMutable();
        name_.add(builderForValue.build());
        onChanged();
      } else {
        nameBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .google.protobuf.UninterpretedOption.NamePart name = 2;</code>
     */
    public Builder addName(
        int index, com.google.protobuf.UninterpretedOption.NamePart.Builder builderForValue) {
      if (nameBuilder_ == null) {
        ensureNameIsMutable();
        name_.add(index, builderForValue.build());
        onChanged();
      } else {
        nameBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .google.protobuf.UninterpretedOption.NamePart name = 2;</code>
     */
    public Builder addAllName(
        java.lang.Iterable<? extends com.google.protobuf.UninterpretedOption.NamePart> values) {
      if (nameBuilder_ == null) {
        ensureNameIsMutable();
        super.addAll(values, name_);
        onChanged();
      } else {
        nameBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .google.protobuf.UninterpretedOption.NamePart name = 2;</code>
     */
    public Builder clearName() {
      if (nameBuilder_ == null) {
        name_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        nameBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .google.protobuf.UninterpretedOption.NamePart name = 2;</code>
     */
    public Builder removeName(int index) {
      if (nameBuilder_ == null) {
        ensureNameIsMutable();
        name_.remove(index);
        onChanged();
      } else {
        nameBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .google.protobuf.UninterpretedOption.NamePart name = 2;</code>
     */
    public com.google.protobuf.UninterpretedOption.NamePart.Builder getNameBuilder(
        int index) {
      return getNameFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .google.protobuf.UninterpretedOption.NamePart name = 2;</code>
     */
    public com.google.protobuf.UninterpretedOption.NamePartOrBuilder getNameOrBuilder(
        int index) {
      if (nameBuilder_ == null) {
        return name_.get(index);  } else {
        return nameBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .google.protobuf.UninterpretedOption.NamePart name = 2;</code>
     */
    public java.util.List<? extends com.google.protobuf.UninterpretedOption.NamePartOrBuilder> 
         getNameOrBuilderList() {
      if (nameBuilder_ != null) {
        return nameBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(name_);
      }
    }
    /**
     * <code>repeated .google.protobuf.UninterpretedOption.NamePart name = 2;</code>
     */
    public com.google.protobuf.UninterpretedOption.NamePart.Builder addNameBuilder() {
      return getNameFieldBuilder().addBuilder(
          com.google.protobuf.UninterpretedOption.NamePart.getDefaultInstance());
    }
    /**
     * <code>repeated .google.protobuf.UninterpretedOption.NamePart name = 2;</code>
     */
    public com.google.protobuf.UninterpretedOption.NamePart.Builder addNameBuilder(
        int index) {
      return getNameFieldBuilder().addBuilder(
          index, com.google.protobuf.UninterpretedOption.NamePart.getDefaultInstance());
    }
    /**
     * <code>repeated .google.protobuf.UninterpretedOption.NamePart name = 2;</code>
     */
    public java.util.List<com.google.protobuf.UninterpretedOption.NamePart.Builder> 
         getNameBuilderList() {
      return getNameFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilder<
        com.google.protobuf.UninterpretedOption.NamePart, com.google.protobuf.UninterpretedOption.NamePart.Builder, com.google.protobuf.UninterpretedOption.NamePartOrBuilder> 
        getNameFieldBuilder() {
      if (nameBuilder_ == null) {
        nameBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
            com.google.protobuf.UninterpretedOption.NamePart, com.google.protobuf.UninterpretedOption.NamePart.Builder, com.google.protobuf.UninterpretedOption.NamePartOrBuilder>(
                name_,
                ((bitField0_ & 0x00000001) == 0x00000001),
                getParentForChildren(),
                isClean());
        name_ = null;
      }
      return nameBuilder_;
    }

    // optional string identifier_value = 3;
    private java.lang.Object identifierValue_ = "";
    /**
     * <code>optional string identifier_value = 3;</code>
     *
     * <pre>
     * The value of the uninterpreted option, in whatever type the tokenizer
     * identified it as during parsing. Exactly one of these should be set.
     * </pre>
     */
    public boolean hasIdentifierValue() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string identifier_value = 3;</code>
     *
     * <pre>
     * The value of the uninterpreted option, in whatever type the tokenizer
     * identified it as during parsing. Exactly one of these should be set.
     * </pre>
     */
    public java.lang.String getIdentifierValue() {
      java.lang.Object ref = identifierValue_;
      if (!(ref instanceof java.lang.String)) {
        java.lang.String s = ((com.google.protobuf.ByteString) ref)
            .toStringUtf8();
        identifierValue_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string identifier_value = 3;</code>
     *
     * <pre>
     * The value of the uninterpreted option, in whatever type the tokenizer
     * identified it as during parsing. Exactly one of these should be set.
     * </pre>
     */
    public com.google.protobuf.ByteString
        getIdentifierValueBytes() {
      java.lang.Object ref = identifierValue_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        identifierValue_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string identifier_value = 3;</code>
     *
     * <pre>
     * The value of the uninterpreted option, in whatever type the tokenizer
     * identified it as during parsing. Exactly one of these should be set.
     * </pre>
     */
    public Builder setIdentifierValue(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
      identifierValue_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string identifier_value = 3;</code>
     *
     * <pre>
     * The value of the uninterpreted option, in whatever type the tokenizer
     * identified it as during parsing. Exactly one of these should be set.
     * </pre>
     */
    public Builder clearIdentifierValue() {
      bitField0_ = (bitField0_ & ~0x00000002);
      identifierValue_ = getDefaultInstance().getIdentifierValue();
      onChanged();
      return this;
    }
    /**
     * <code>optional string identifier_value = 3;</code>
     *
     * <pre>
     * The value of the uninterpreted option, in whatever type the tokenizer
     * identified it as during parsing. Exactly one of these should be set.
     * </pre>
     */
    public Builder setIdentifierValueBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
      identifierValue_ = value;
      onChanged();
      return this;
    }

    // optional uint64 positive_int_value = 4;
    private long positiveIntValue_ ;
    /**
     * <code>optional uint64 positive_int_value = 4;</code>
     */
    public boolean hasPositiveIntValue() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional uint64 positive_int_value = 4;</code>
     */
    public long getPositiveIntValue() {
      return positiveIntValue_;
    }
    /**
     * <code>optional uint64 positive_int_value = 4;</code>
     */
    public Builder setPositiveIntValue(long value) {
      bitField0_ |= 0x00000004;
      positiveIntValue_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional uint64 positive_int_value = 4;</code>
     */
    public Builder clearPositiveIntValue() {
      bitField0_ = (bitField0_ & ~0x00000004);
      positiveIntValue_ = 0L;
      onChanged();
      return this;
    }

    // optional int64 negative_int_value = 5;
    private long negativeIntValue_ ;
    /**
     * <code>optional int64 negative_int_value = 5;</code>
     */
    public boolean hasNegativeIntValue() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional int64 negative_int_value = 5;</code>
     */
    public long getNegativeIntValue() {
      return negativeIntValue_;
    }
    /**
     * <code>optional int64 negative_int_value = 5;</code>
     */
    public Builder setNegativeIntValue(long value) {
      bitField0_ |= 0x00000008;
      negativeIntValue_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional int64 negative_int_value = 5;</code>
     */
    public Builder clearNegativeIntValue() {
      bitField0_ = (bitField0_ & ~0x00000008);
      negativeIntValue_ = 0L;
      onChanged();
      return this;
    }

    // optional double double_value = 6;
    private double doubleValue_ ;
    /**
     * <code>optional double double_value = 6;</code>
     */
    public boolean hasDoubleValue() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional double double_value = 6;</code>
     */
    public double getDoubleValue() {
      return doubleValue_;
    }
    /**
     * <code>optional double double_value = 6;</code>
     */
    public Builder setDoubleValue(double value) {
      bitField0_ |= 0x00000010;
      doubleValue_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional double double_value = 6;</code>
     */
    public Builder clearDoubleValue() {
      bitField0_ = (bitField0_ & ~0x00000010);
      doubleValue_ = 0D;
      onChanged();
      return this;
    }

    // optional bytes string_value = 7;
    private com.google.protobuf.ByteString stringValue_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <code>optional bytes string_value = 7;</code>
     */
    public boolean hasStringValue() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>optional bytes string_value = 7;</code>
     */
    public com.google.protobuf.ByteString getStringValue() {
      return stringValue_;
    }
    /**
     * <code>optional bytes string_value = 7;</code>
     */
    public Builder setStringValue(com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
      stringValue_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional bytes string_value = 7;</code>
     */
    public Builder clearStringValue() {
      bitField0_ = (bitField0_ & ~0x00000020);
      stringValue_ = getDefaultInstance().getStringValue();
      onChanged();
      return this;
    }

    // optional string aggregate_value = 8;
    private java.lang.Object aggregateValue_ = "";
    /**
     * <code>optional string aggregate_value = 8;</code>
     */
    public boolean hasAggregateValue() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    /**
     * <code>optional string aggregate_value = 8;</code>
     */
    public java.lang.String getAggregateValue() {
      java.lang.Object ref = aggregateValue_;
      if (!(ref instanceof java.lang.String)) {
        java.lang.String s = ((com.google.protobuf.ByteString) ref)
            .toStringUtf8();
        aggregateValue_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string aggregate_value = 8;</code>
     */
    public com.google.protobuf.ByteString
        getAggregateValueBytes() {
      java.lang.Object ref = aggregateValue_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        aggregateValue_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string aggregate_value = 8;</code>
     */
    public Builder setAggregateValue(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
      aggregateValue_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string aggregate_value = 8;</code>
     */
    public Builder clearAggregateValue() {
      bitField0_ = (bitField0_ & ~0x00000040);
      aggregateValue_ = getDefaultInstance().getAggregateValue();
      onChanged();
      return this;
    }
    /**
     * <code>optional string aggregate_value = 8;</code>
     */
    public Builder setAggregateValueBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
      aggregateValue_ = value;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:google.protobuf.UninterpretedOption)
  }

  static {
    defaultInstance = new UninterpretedOption(true);
    defaultInstance.initFields();
  }

  // @@protoc_insertion_point(class_scope:google.protobuf.UninterpretedOption)
}

