package org.ripple.power.txns.btc;

public enum BTCStore {

	BITSTAMP, COINBASE, BTC38, BTER, BITCOIN_AVERAGE, BITCOINDE, BITCUREX, BITFINEX, BITCOIN_AVERAGE_GLOBAL, BTC_CHINA, BITPAY, KRAKEN, BTCTURK, VIRTEX, JUSTCOIN, LAKEBTC, CRYPTONIT, COINTREE, BTCMARKETS, HUOBI, KORBIT, PAYMIUM, BITSO, ZYADO, CRYPTSY, BITBAY, CEXIO, HITBTC, ITBIT, BITCOINCOID, FOXBIT, INDEPENDENT_RESERVER, CLEVERCOIN, BITMARKET24, QUADRIGA, GATECOIN, MEXBT, OKCOIN,
}
