var hasOwn=Object.prototype.hasOwnProperty,toString=Object.prototype.toString,isPlainObject=function(a){if(!a||toString.call(a)!=="[object Object]")return!1;var b=hasOwn.call(a,"constructor"),c=a.constructor&&a.constructor.prototype&&hasOwn.call(a.constructor.prototype,"isPrototypeOf");if(a.constructor&&!b&&!c)return!1;for(var d in a);return d===void 0||hasOwn.call(a,d)};
function extend(){var a,b,c,d,e,f=arguments[0],g=1,h=arguments.length,i=!1;if(typeof f==="boolean")i=f,f=arguments[1]||{},g=2;else if(typeof f!=="object"&&typeof f!=="function"||f==null)f={};for(;g<h;++g)if(a=arguments[g],a!=null)for(b in a)c=f[b],d=a[b],f!==d&&(i&&d&&(isPlainObject(d)||(e=Array.isArray(d)))?(e?(e=!1,c=c&&Array.isArray(c)?c:[]):c=c&&isPlainObject(c)?c:{},f[b]=extend(i,c,d)):d!==void 0&&(f[b]=d));return f}
var sjcl={cipher:{},hash:{},keyexchange:{},mode:{},misc:{},codec:{},exception:{corrupt:function(a){this.toString=function(){return"CORRUPT: "+this.message};this.message=a},invalid:function(a){this.toString=function(){return"INVALID: "+this.message};this.message=a},bug:function(a){this.toString=function(){return"BUG: "+this.message};this.message=a},notReady:function(a){this.toString=function(){return"NOT READY: "+this.message};this.message=a}}};
if(typeof module!="undefined"&&module.exports)module.exports=sjcl;sjcl.cipher.aes=function(a){this._tables[0][0][0]||this._precompute();var b,c,d;b=this._tables[0][4];var e=a.length,f=1;if(e!==4&&e!==6&&e!==8)throw new sjcl.exception.invalid("invalid aes key size");this._key=[d=a.slice(0),[]];for(a=e;a<4*e+28;a++){c=d[a-1];if(a%e===0||e===8&&a%e===4)c=b[c>>>24]<<24^b[c>>16&255]<<16^b[c>>8&255]<<8^b[c&255],a%e===0&&(c=c<<8^c>>>24^f<<24,f=f<<1^(f>>7)*283);d[a]=d[a-e]^c}for(b=0;a;b++,a--);};
sjcl.cipher.aes.prototype={encrypt:function(a){return this._crypt(a,0)},decrypt:function(a){return this._crypt(a,1)},_tables:[[[],[],[],[],[]],[[],[],[],[],[]]],_precompute:function(){var a=this._tables[0],b=this._tables[1],c=a[4],d=b[4],e,f,g,h=[],i=[],k,l,m,q;for(e=0;e<256;e++)i[(h[e]=e<<1^(e>>7)*283)^e]=e;for(f=g=0;!c[f];f^=k||1,g=i[g]||1){m=g^g<<1^g<<2^g<<3^g<<4;m=m>>8^m&255^99;c[f]=m;d[m]=f;l=h[e=h[k=h[f]]];q=l*16843009^e*65537^k*257^f*16843008;l=h[m]*257^m*16843008;for(e=0;e<4;e++)a[e][f]=l=
l<<24^l>>>8,b[e][m]=q=q<<24^q>>>8}for(e=0;e<5;e++)a[e]=a[e].slice(0),b[e]=b[e].slice(0)},_crypt:function(a,b){if(a.length!==4)throw new sjcl.exception.invalid("invalid aes block size");var c=this._key[b],d=a[0]^c[0],e=a[b?3:1]^c[1],f=a[2]^c[2],g=a[b?1:3]^c[3],h,i,k,l=c.length/4-2,m,q=4,t=[0,0,0,0];h=this._tables[b];var z=h[0],B=h[1],D=h[2],p=h[3],u=h[4];for(m=0;m<l;m++)h=z[d>>>24]^B[e>>16&255]^D[f>>8&255]^p[g&255]^c[q],i=z[e>>>24]^B[f>>16&255]^D[g>>8&255]^p[d&255]^c[q+1],k=z[f>>>24]^B[g>>16&255]^
D[d>>8&255]^p[e&255]^c[q+2],g=z[g>>>24]^B[d>>16&255]^D[e>>8&255]^p[f&255]^c[q+3],q+=4,d=h,e=i,f=k;for(m=0;m<4;m++)t[b?3&-m:m]=u[d>>>24]<<24^u[e>>16&255]<<16^u[f>>8&255]<<8^u[g&255]^c[q++],h=d,d=e,e=f,f=g,g=h;return t}};
sjcl.bitArray={bitSlice:function(a,b,c){a=sjcl.bitArray._shiftRight(a.slice(b/32),32-(b&31)).slice(1);return c===void 0?a:sjcl.bitArray.clamp(a,c-b)},extract:function(a,b,c){var d=Math.floor(-b-c&31);return((b+c-1^b)&-32?a[b/32|0]<<32-d^a[b/32+1|0]>>>d:a[b/32|0]>>>d)&(1<<c)-1},concat:function(a,b){if(a.length===0||b.length===0)return a.concat(b);var c=a[a.length-1],d=sjcl.bitArray.getPartial(c);return d===32?a.concat(b):sjcl.bitArray._shiftRight(b,d,c|0,a.slice(0,a.length-1))},bitLength:function(a){var b=
a.length;return b===0?0:(b-1)*32+sjcl.bitArray.getPartial(a[b-1])},clamp:function(a,b){if(a.length*32<b)return a;var a=a.slice(0,Math.ceil(b/32)),c=a.length;b&=31;c>0&&b&&(a[c-1]=sjcl.bitArray.partial(b,a[c-1]&2147483648>>b-1,1));return a},partial:function(a,b,c){return a===32?b:(c?b|0:b<<32-a)+a*1099511627776},getPartial:function(a){return Math.round(a/1099511627776)||32},equal:function(a,b){if(sjcl.bitArray.bitLength(a)!==sjcl.bitArray.bitLength(b))return!1;var c=0,d;for(d=0;d<a.length;d++)c|=a[d]^
b[d];return c===0},_shiftRight:function(a,b,c,d){var e;e=0;for(d===void 0&&(d=[]);b>=32;b-=32)d.push(c),c=0;if(b===0)return d.concat(a);for(e=0;e<a.length;e++)d.push(c|a[e]>>>b),c=a[e]<<32-b;e=a.length?a[a.length-1]:0;a=sjcl.bitArray.getPartial(e);d.push(sjcl.bitArray.partial(b+a&31,b+a>32?c:d.pop(),1));return d},_xor4:function(a,b){return[a[0]^b[0],a[1]^b[1],a[2]^b[2],a[3]^b[3]]}};
sjcl.codec.utf8String={fromBits:function(a){var b="",c=sjcl.bitArray.bitLength(a),d,e;for(d=0;d<c/8;d++)(d&3)===0&&(e=a[d/4]),b+=String.fromCharCode(e>>>24),e<<=8;return decodeURIComponent(escape(b))},toBits:function(a){var a=unescape(encodeURIComponent(a)),b=[],c,d=0;for(c=0;c<a.length;c++)d=d<<8|a.charCodeAt(c),(c&3)===3&&(b.push(d),d=0);c&3&&b.push(sjcl.bitArray.partial(8*(c&3),d));return b}};
sjcl.codec.hex={fromBits:function(a){var b="",c;for(c=0;c<a.length;c++)b+=((a[c]|0)+263882790666240).toString(16).substr(4);return b.substr(0,sjcl.bitArray.bitLength(a)/4)},toBits:function(a){var b,c=[],d,a=a.replace(/\s|0x/g,"");d=a.length;a+="00000000";for(b=0;b<a.length;b+=8)c.push(parseInt(a.substr(b,8),16)^0);return sjcl.bitArray.clamp(c,d*4)}};
sjcl.codec.base64={_chars:"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/",fromBits:function(a,b,c){var d="",e=0,f=sjcl.codec.base64._chars,g=0,h=sjcl.bitArray.bitLength(a);c&&(f=f.substr(0,62)+"-_");for(c=0;d.length*6<h;)d+=f.charAt((g^a[c]>>>e)>>>26),e<6?(g=a[c]<<6-e,e+=26,c++):(g<<=6,e-=6);for(;d.length&3&&!b;)d+="=";return d},toBits:function(a,b){var a=a.replace(/\s|=/g,""),c=[],d,e=0,f=sjcl.codec.base64._chars,g=0,h;b&&(f=f.substr(0,62)+"-_");for(d=0;d<a.length;d++){h=f.indexOf(a.charAt(d));
if(h<0)throw new sjcl.exception.invalid("this isn't base64!");e>26?(e-=26,c.push(g^h>>>e),g=h<<32-e):(e+=6,g^=h<<32-e)}e&56&&c.push(sjcl.bitArray.partial(e&56,g,1));return c}};sjcl.codec.base64url={fromBits:function(a){return sjcl.codec.base64.fromBits(a,1,1)},toBits:function(a){return sjcl.codec.base64.toBits(a,1)}};
sjcl.codec.bytes={fromBits:function(a){var b=[],c=sjcl.bitArray.bitLength(a),d,e;for(d=0;d<c/8;d++)(d&3)===0&&(e=a[d/4]),b.push(e>>>24),e<<=8;return b},toBits:function(a){var b=[],c,d=0;for(c=0;c<a.length;c++)d=d<<8|a[c],(c&3)===3&&(b.push(d),d=0);c&3&&b.push(sjcl.bitArray.partial(8*(c&3),d));return b}};sjcl.hash.sha256=function(a){this._key[0]||this._precompute();a?(this._h=a._h.slice(0),this._buffer=a._buffer.slice(0),this._length=a._length):this.reset()};sjcl.hash.sha256.hash=function(a){return(new sjcl.hash.sha256).update(a).finalize()};
sjcl.hash.sha256.prototype={blockSize:512,reset:function(){this._h=this._init.slice(0);this._buffer=[];this._length=0;return this},update:function(a){typeof a==="string"&&(a=sjcl.codec.utf8String.toBits(a));var b,c=this._buffer=sjcl.bitArray.concat(this._buffer,a);b=this._length;a=this._length=b+sjcl.bitArray.bitLength(a);for(b=512+b&-512;b<=a;b+=512)this._block(c.splice(0,16));return this},finalize:function(){var a,b=this._buffer,c=this._h,b=sjcl.bitArray.concat(b,[sjcl.bitArray.partial(1,1)]);for(a=
b.length+2;a&15;a++)b.push(0);b.push(Math.floor(this._length/4294967296));for(b.push(this._length|0);b.length;)this._block(b.splice(0,16));this.reset();return c},_init:[],_key:[],_precompute:function(){var a=0,b=2,c;a:for(;a<64;b++){for(c=2;c*c<=b;c++)if(b%c===0)continue a;a<8&&(this._init[a]=(Math.pow(b,0.5)-Math.floor(Math.pow(b,0.5)))*4294967296|0);this._key[a]=(Math.pow(b,1/3)-Math.floor(Math.pow(b,1/3)))*4294967296|0;a++}},_block:function(a){for(var b,c,d=a.slice(0),e=this._h,f=this._key,g=e[0],
h=e[1],i=e[2],k=e[3],l=e[4],m=e[5],q=e[6],t=e[7],a=0;a<64;a++)a<16?b=d[a]:(b=d[a+1&15],c=d[a+14&15],b=d[a&15]=(b>>>7^b>>>18^b>>>3^b<<25^b<<14)+(c>>>17^c>>>19^c>>>10^c<<15^c<<13)+d[a&15]+d[a+9&15]|0),b=b+t+(l>>>6^l>>>11^l>>>25^l<<26^l<<21^l<<7)+(q^l&(m^q))+f[a],t=q,q=m,m=l,l=k+b|0,k=i,i=h,h=g,g=b+(h&i^k&(h^i))+(h>>>2^h>>>13^h>>>22^h<<30^h<<19^h<<10)|0;e[0]=e[0]+g|0;e[1]=e[1]+h|0;e[2]=e[2]+i|0;e[3]=e[3]+k|0;e[4]=e[4]+l|0;e[5]=e[5]+m|0;e[6]=e[6]+q|0;e[7]=e[7]+t|0}};
sjcl.hash.sha512=function(a){this._key[0]||this._precompute();a?(this._h=a._h.slice(0),this._buffer=a._buffer.slice(0),this._length=a._length):this.reset()};sjcl.hash.sha512.hash=function(a){return(new sjcl.hash.sha512).update(a).finalize()};
sjcl.hash.sha512.prototype={blockSize:1024,reset:function(){this._h=this._init.slice(0);this._buffer=[];this._length=0;return this},update:function(a){typeof a==="string"&&(a=sjcl.codec.utf8String.toBits(a));var b,c=this._buffer=sjcl.bitArray.concat(this._buffer,a);b=this._length;a=this._length=b+sjcl.bitArray.bitLength(a);for(b=1024+b&-1024;b<=a;b+=1024)this._block(c.splice(0,32));return this},finalize:function(){var a,b=this._buffer,c=this._h,b=sjcl.bitArray.concat(b,[sjcl.bitArray.partial(1,1)]);
for(a=b.length+4;a&31;a++)b.push(0);b.push(0);b.push(0);b.push(Math.floor(this._length/4294967296));for(b.push(this._length|0);b.length;)this._block(b.splice(0,32));this.reset();return c},_init:[],_initr:[12372232,13281083,9762859,1914609,15106769,4090911,4308331,8266105],_key:[],_keyr:[2666018,15689165,5061423,9034684,4764984,380953,1658779,7176472,197186,7368638,14987916,16757986,8096111,1480369,13046325,6891156,15813330,5187043,9229749,11312229,2818677,10937475,4324308,1135541,6741931,11809296,
16458047,15666916,11046850,698149,229999,945776,13774844,2541862,12856045,9810911,11494366,7844520,15576806,8533307,15795044,4337665,16291729,5553712,15684120,6662416,7413802,12308920,13816008,4303699,9366425,10176680,13195875,4295371,6546291,11712675,15708924,1519456,15772530,6568428,6495784,8568297,13007125,7492395,2515356,12632583,14740254,7262584,1535930,13146278,16321966,1853211,294276,13051027,13221564,1051980,4080310,6651434,14088940,4675607],_precompute:function(){var a=0,b=2,c;a:for(;a<80;b++){for(c=
2;c*c<=b;c++)if(b%c===0)continue a;a<8&&(this._init[a*2]=(Math.pow(b,0.5)-Math.floor(Math.pow(b,0.5)))*4294967296|0,this._init[a*2+1]=((Math.pow(b,0.5)-Math.floor(Math.pow(b,0.5)))*1099511627776&255)<<24|this._initr[a]);this._key[a*2]=(Math.pow(b,1/3)-Math.floor(Math.pow(b,1/3)))*4294967296|0;this._key[a*2+1]=((Math.pow(b,1/3)-Math.floor(Math.pow(b,1/3)))*1099511627776&255)<<24|this._keyr[a];a++}},_block:function(a){for(var b,c,d=a.slice(0),e=this._h,f=this._key,g=e[0],h=e[1],i=e[2],k=e[3],l=e[4],
m=e[5],q=e[6],t=e[7],z=e[8],B=e[9],D=e[10],p=e[11],u=e[12],r=e[13],v=e[14],s=e[15],n=g,j=h,o=i,E=k,G=l,F=m,O=q,H=t,y=z,x=B,M=D,I=p,N=u,J=r,P=v,K=s,a=0;a<80;a++){if(a<16)b=d[a*2],c=d[a*2+1];else{c=d[(a-15)*2];var w=d[(a-15)*2+1];b=(w<<31|c>>>1)^(w<<24|c>>>8)^c>>>7;var C=(c<<31|w>>>1)^(c<<24|w>>>8)^(c<<25|w>>>7);c=d[(a-2)*2];var A=d[(a-2)*2+1],w=(A<<13|c>>>19)^(c<<3|A>>>29)^c>>>6,A=(c<<13|A>>>19)^(A<<3|c>>>29)^(c<<26|A>>>6),Q=d[(a-7)*2],R=d[(a-16)*2],L=d[(a-16)*2+1];c=C+d[(a-7)*2+1];b=b+Q+(c>>>0<C>>>
0?1:0);c+=A;b+=w+(c>>>0<A>>>0?1:0);c+=L;b+=R+(c>>>0<L>>>0?1:0)}d[a*2]=b|=0;d[a*2+1]=c|=0;var Q=y&M^~y&N,S=x&I^~x&J,A=n&o^n&G^o&G,U=j&E^j&F^E&F,R=(j<<4|n>>>28)^(n<<30|j>>>2)^(n<<25|j>>>7),L=(n<<4|j>>>28)^(j<<30|n>>>2)^(j<<25|n>>>7),V=f[a*2],T=f[a*2+1],w=K+((y<<18|x>>>14)^(y<<14|x>>>18)^(x<<23|y>>>9)),C=P+((x<<18|y>>>14)^(x<<14|y>>>18)^(y<<23|x>>>9))+(w>>>0<K>>>0?1:0);w+=S;C+=Q+(w>>>0<S>>>0?1:0);w+=T;C+=V+(w>>>0<T>>>0?1:0);w+=c;C+=b+(w>>>0<c>>>0?1:0);c=L+U;b=R+A+(c>>>0<L>>>0?1:0);P=N;K=J;N=M;J=I;M=
y;I=x;x=H+w|0;y=O+C+(x>>>0<H>>>0?1:0)|0;O=G;H=F;G=o;F=E;o=n;E=j;j=w+c|0;n=C+b+(j>>>0<w>>>0?1:0)|0}h=e[1]=h+j|0;e[0]=g+n+(h>>>0<j>>>0?1:0)|0;k=e[3]=k+E|0;e[2]=i+o+(k>>>0<E>>>0?1:0)|0;m=e[5]=m+F|0;e[4]=l+G+(m>>>0<F>>>0?1:0)|0;t=e[7]=t+H|0;e[6]=q+O+(t>>>0<H>>>0?1:0)|0;B=e[9]=B+x|0;e[8]=z+y+(B>>>0<x>>>0?1:0)|0;p=e[11]=p+I|0;e[10]=D+M+(p>>>0<I>>>0?1:0)|0;r=e[13]=r+J|0;e[12]=u+N+(r>>>0<J>>>0?1:0)|0;s=e[15]=s+K|0;e[14]=v+P+(s>>>0<K>>>0?1:0)|0}};
sjcl.hash.sha1=function(a){a?(this._h=a._h.slice(0),this._buffer=a._buffer.slice(0),this._length=a._length):this.reset()};sjcl.hash.sha1.hash=function(a){return(new sjcl.hash.sha1).update(a).finalize()};
sjcl.hash.sha1.prototype={blockSize:512,reset:function(){this._h=this._init.slice(0);this._buffer=[];this._length=0;return this},update:function(a){typeof a==="string"&&(a=sjcl.codec.utf8String.toBits(a));var b,c=this._buffer=sjcl.bitArray.concat(this._buffer,a);b=this._length;a=this._length=b+sjcl.bitArray.bitLength(a);for(b=this.blockSize+b&-this.blockSize;b<=a;b+=this.blockSize)this._block(c.splice(0,16));return this},finalize:function(){var a,b=this._buffer,c=this._h,b=sjcl.bitArray.concat(b,
[sjcl.bitArray.partial(1,1)]);for(a=b.length+2;a&15;a++)b.push(0);b.push(Math.floor(this._length/4294967296));for(b.push(this._length|0);b.length;)this._block(b.splice(0,16));this.reset();return c},_init:[1732584193,4023233417,2562383102,271733878,3285377520],_key:[1518500249,1859775393,2400959708,3395469782],_f:function(a,b,c,d){if(a<=19)return b&c|~b&d;else if(a<=39)return b^c^d;else if(a<=59)return b&c|b&d|c&d;else if(a<=79)return b^c^d},_S:function(a,b){return b<<a|b>>>32-a},_block:function(a){var b,
c,d,e,f,g,h=a.slice(0),i=this._h;c=i[0];d=i[1];e=i[2];f=i[3];g=i[4];for(a=0;a<=79;a++)a>=16&&(h[a]=this._S(1,h[a-3]^h[a-8]^h[a-14]^h[a-16])),b=this._S(5,c)+this._f(a,d,e,f)+g+h[a]+this._key[Math.floor(a/20)]|0,g=f,f=e,e=this._S(30,d),d=c,c=b;i[0]=i[0]+c|0;i[1]=i[1]+d|0;i[2]=i[2]+e|0;i[3]=i[3]+f|0;i[4]=i[4]+g|0}};
sjcl.mode.ccm={name:"ccm",encrypt:function(a,b,c,d,e){var f,g=b.slice(0),h=sjcl.bitArray,i=h.bitLength(c)/8,k=h.bitLength(g)/8,e=e||64,d=d||[];if(i<7)throw new sjcl.exception.invalid("ccm: iv must be at least 7 bytes");for(f=2;f<4&&k>>>8*f;f++);f<15-i&&(f=15-i);c=h.clamp(c,8*(15-f));b=sjcl.mode.ccm._computeTag(a,b,c,d,e,f);g=sjcl.mode.ccm._ctrMode(a,g,c,b,e,f);return h.concat(g.data,g.tag)},decrypt:function(a,b,c,d,e){var e=e||64,d=d||[],f=sjcl.bitArray,g=f.bitLength(c)/8,h=f.bitLength(b),i=f.clamp(b,
h-e),k=f.bitSlice(b,h-e),h=(h-e)/8;if(g<7)throw new sjcl.exception.invalid("ccm: iv must be at least 7 bytes");for(b=2;b<4&&h>>>8*b;b++);b<15-g&&(b=15-g);c=f.clamp(c,8*(15-b));i=sjcl.mode.ccm._ctrMode(a,i,c,k,e,b);a=sjcl.mode.ccm._computeTag(a,i.data,c,d,e,b);if(!f.equal(i.tag,a))throw new sjcl.exception.corrupt("ccm: tag doesn't match");return i.data},_computeTag:function(a,b,c,d,e,f){var g=[],h=sjcl.bitArray,i=h._xor4;e/=8;if(e%2||e<4||e>16)throw new sjcl.exception.invalid("ccm: invalid tag length");
if(d.length>4294967295||b.length>4294967295)throw new sjcl.exception.bug("ccm: can't deal with 4GiB or more data");f=[h.partial(8,(d.length?64:0)|e-2<<2|f-1)];f=h.concat(f,c);f[3]|=h.bitLength(b)/8;f=a.encrypt(f);if(d.length){c=h.bitLength(d)/8;c<=65279?g=[h.partial(16,c)]:c<=4294967295&&(g=h.concat([h.partial(16,65534)],[c]));g=h.concat(g,d);for(d=0;d<g.length;d+=4)f=a.encrypt(i(f,g.slice(d,d+4).concat([0,0,0])))}for(d=0;d<b.length;d+=4)f=a.encrypt(i(f,b.slice(d,d+4).concat([0,0,0])));return h.clamp(f,
e*8)},_ctrMode:function(a,b,c,d,e,f){var g,h=sjcl.bitArray;g=h._xor4;var i=b.length,k=h.bitLength(b),c=h.concat([h.partial(8,f-1)],c).concat([0,0,0]).slice(0,4),d=h.bitSlice(g(d,a.encrypt(c)),0,e);if(!i)return{tag:d,data:[]};for(g=0;g<i;g+=4)c[3]++,e=a.encrypt(c),b[g]^=e[0],b[g+1]^=e[1],b[g+2]^=e[2],b[g+3]^=e[3];return{tag:d,data:h.clamp(b,k)}}};
sjcl.misc.hmac=function(a,b){this._hash=b=b||sjcl.hash.sha256;var c=[[],[]],d,e=b.prototype.blockSize/32;this._baseHash=[new b,new b];a.length>e&&(a=b.hash(a));for(d=0;d<e;d++)c[0][d]=a[d]^909522486,c[1][d]=a[d]^1549556828;this._baseHash[0].update(c[0]);this._baseHash[1].update(c[1])};sjcl.misc.hmac.prototype.encrypt=sjcl.misc.hmac.prototype.mac=function(a){a=(new this._hash(this._baseHash[0])).update(a).finalize();return(new this._hash(this._baseHash[1])).update(a).finalize()};
sjcl.misc.pbkdf2=function(a,b,c,d,e){c=c||1E3;if(d<0||c<0)throw sjcl.exception.invalid("invalid params to pbkdf2");typeof a==="string"&&(a=sjcl.codec.utf8String.toBits(a));var e=e||sjcl.misc.hmac,a=new e(a),f,g,h,i,k=[],l=sjcl.bitArray;for(i=1;32*k.length<(d||1);i++){e=f=a.encrypt(l.concat(b,[i]));for(g=1;g<c;g++){f=a.encrypt(f);for(h=0;h<f.length;h++)e[h]^=f[h]}k=k.concat(e)}d&&(k=l.clamp(k,d));return k};
sjcl.prng=function(a){this._pools=[new sjcl.hash.sha256];this._poolEntropy=[0];this._reseedCount=0;this._robins={};this._eventId=0;this._collectorIds={};this._nextReseed=this._poolStrength=this._strength=this._collectorIdNext=0;this._key=[0,0,0,0,0,0,0,0];this._counter=[0,0,0,0];this._cipher=void 0;this._defaultParanoia=a;this._collectorsStarted=!1;this._callbacks={progress:{},seeded:{}};this._NOT_READY=this._callbackI=0;this._READY=1;this._REQUIRES_RESEED=2;this._MAX_WORDS_PER_BURST=65536;this._PARANOIA_LEVELS=
[0,48,64,96,128,192,256,384,512,768,1024];this._MILLISECONDS_PER_RESEED=3E4;this._BITS_PER_RESEED=80};
sjcl.prng.prototype={randomWords:function(a,b){var c=[],d;d=this.isReady(b);var e;if(d===this._NOT_READY)throw new sjcl.exception.notReady("generator isn't seeded");else d&this._REQUIRES_RESEED&&this._reseedFromPools(!(d&this._READY));for(d=0;d<a;d+=4)(d+1)%this._MAX_WORDS_PER_BURST===0&&this._gate(),e=this._gen4words(),c.push(e[0],e[1],e[2],e[3]);this._gate();return c.slice(0,a)},setDefaultParanoia:function(a){this._defaultParanoia=a},addEntropy:function(a,b,c){var c=c||"user",d,e,f=(new Date).valueOf(),
g=this._robins[c],h=this.isReady(),i=0;d=this._collectorIds[c];d===void 0&&(d=this._collectorIds[c]=this._collectorIdNext++);g===void 0&&(g=this._robins[c]=0);this._robins[c]=(this._robins[c]+1)%this._pools.length;switch(typeof a){case "number":b===void 0&&(b=1);this._pools[g].update([d,this._eventId++,1,b,f,1,a|0]);break;case "object":c=Object.prototype.toString.call(a);if(c==="[object Uint32Array]"){e=[];for(c=0;c<a.length;c++)e.push(a[c]);a=e}else{c!=="[object Array]"&&(i=1);for(c=0;c<a.length&&
!i;c++)typeof a[c]!="number"&&(i=1)}if(!i){if(b===void 0)for(c=b=0;c<a.length;c++)for(e=a[c];e>0;)b++,e>>>=1;this._pools[g].update([d,this._eventId++,2,b,f,a.length].concat(a))}break;case "string":if(b===void 0)b=a.length;this._pools[g].update([d,this._eventId++,3,b,f,a.length]);this._pools[g].update(a);break;default:i=1}if(i)throw new sjcl.exception.bug("random: addEntropy only supports number, array of numbers or string");this._poolEntropy[g]+=b;this._poolStrength+=b;h===this._NOT_READY&&(this.isReady()!==
this._NOT_READY&&this._fireEvent("seeded",Math.max(this._strength,this._poolStrength)),this._fireEvent("progress",this.getProgress()))},isReady:function(a){a=this._PARANOIA_LEVELS[a!==void 0?a:this._defaultParanoia];return this._strength&&this._strength>=a?this._poolEntropy[0]>this._BITS_PER_RESEED&&(new Date).valueOf()>this._nextReseed?this._REQUIRES_RESEED|this._READY:this._READY:this._poolStrength>=a?this._REQUIRES_RESEED|this._NOT_READY:this._NOT_READY},getProgress:function(a){a=this._PARANOIA_LEVELS[a?
a:this._defaultParanoia];return this._strength>=a?1:this._poolStrength>a?1:this._poolStrength/a},startCollectors:function(){if(!this._collectorsStarted){if(window.addEventListener)window.addEventListener("load",this._loadTimeCollector,!1),window.addEventListener("mousemove",this._mouseCollector,!1);else if(document.attachEvent)document.attachEvent("onload",this._loadTimeCollector),document.attachEvent("onmousemove",this._mouseCollector);else throw new sjcl.exception.bug("can't attach event");this._collectorsStarted=
!0}},stopCollectors:function(){if(this._collectorsStarted)window.removeEventListener?(window.removeEventListener("load",this._loadTimeCollector,!1),window.removeEventListener("mousemove",this._mouseCollector,!1)):window.detachEvent&&(window.detachEvent("onload",this._loadTimeCollector),window.detachEvent("onmousemove",this._mouseCollector)),this._collectorsStarted=!1},addEventListener:function(a,b){this._callbacks[a][this._callbackI++]=b},removeEventListener:function(a,b){var c,d,e=this._callbacks[a],
f=[];for(d in e)e.hasOwnProperty(d)&&e[d]===b&&f.push(d);for(c=0;c<f.length;c++)d=f[c],delete e[d]},_gen4words:function(){for(var a=0;a<4;a++)if(this._counter[a]=this._counter[a]+1|0,this._counter[a])break;return this._cipher.encrypt(this._counter)},_gate:function(){this._key=this._gen4words().concat(this._gen4words());this._cipher=new sjcl.cipher.aes(this._key)},_reseed:function(a){this._key=sjcl.hash.sha256.hash(this._key.concat(a));this._cipher=new sjcl.cipher.aes(this._key);for(a=0;a<4;a++)if(this._counter[a]=
this._counter[a]+1|0,this._counter[a])break},_reseedFromPools:function(a){var b=[],c=0,d;this._nextReseed=b[0]=(new Date).valueOf()+this._MILLISECONDS_PER_RESEED;for(d=0;d<16;d++)b.push(Math.random()*4294967296|0);for(d=0;d<this._pools.length;d++)if(b=b.concat(this._pools[d].finalize()),c+=this._poolEntropy[d],this._poolEntropy[d]=0,!a&&this._reseedCount&1<<d)break;this._reseedCount>=1<<this._pools.length&&(this._pools.push(new sjcl.hash.sha256),this._poolEntropy.push(0));this._poolStrength-=c;if(c>
this._strength)this._strength=c;this._reseedCount++;this._reseed(b)},_mouseCollector:function(a){sjcl.random.addEntropy([a.x||a.clientX||a.offsetX||0,a.y||a.clientY||a.offsetY||0],2,"mouse")},_loadTimeCollector:function(){sjcl.random.addEntropy((new Date).valueOf(),2,"loadtime")},_fireEvent:function(a,b){var c,d=sjcl.random._callbacks[a],e=[];for(c in d)d.hasOwnProperty(c)&&e.push(d[c]);for(c=0;c<e.length;c++)e[c](b)}};sjcl.random=new sjcl.prng(6);
(function(){try{var a=new Uint32Array(32);crypto.getRandomValues(a);sjcl.random.addEntropy(a,1024,"crypto.getRandomValues")}catch(b){}})();
sjcl.json={defaults:{v:1,iter:1E3,ks:128,ts:64,mode:"ccm",adata:"",cipher:"aes"},encrypt:function(a,b,c,d){var c=c||{},d=d||{},e=sjcl.json,f=e._add({iv:sjcl.random.randomWords(4,0)},e.defaults),g;e._add(f,c);c=f.adata;if(typeof f.salt==="string")f.salt=sjcl.codec.base64.toBits(f.salt);if(typeof f.iv==="string")f.iv=sjcl.codec.base64.toBits(f.iv);if(!sjcl.mode[f.mode]||!sjcl.cipher[f.cipher]||typeof a==="string"&&f.iter<=100||f.ts!==64&&f.ts!==96&&f.ts!==128||f.ks!==128&&f.ks!==192&&f.ks!==256||f.iv.length<
2||f.iv.length>4)throw new sjcl.exception.invalid("json encrypt: invalid parameters");if(typeof a==="string")g=sjcl.misc.cachedPbkdf2(a,f),a=g.key.slice(0,f.ks/32),f.salt=g.salt;else if(sjcl.ecc&&a instanceof sjcl.ecc.elGamal.publicKey)g=a.kem(),f.kemtag=g.tag,a=g.key.slice(0,f.ks/32);typeof b==="string"&&(b=sjcl.codec.utf8String.toBits(b));typeof c==="string"&&(c=sjcl.codec.utf8String.toBits(c));g=new sjcl.cipher[f.cipher](a);e._add(d,f);d.key=a;f.ct=sjcl.mode[f.mode].encrypt(g,b,f.iv,c,f.ts);return e.encode(f)},
decrypt:function(a,b,c,d){var c=c||{},d=d||{},e=sjcl.json,b=e._add(e._add(e._add({},e.defaults),e.decode(b)),c,!0),f,c=b.adata;if(typeof b.salt==="string")b.salt=sjcl.codec.base64.toBits(b.salt);if(typeof b.iv==="string")b.iv=sjcl.codec.base64.toBits(b.iv);if(!sjcl.mode[b.mode]||!sjcl.cipher[b.cipher]||typeof a==="string"&&b.iter<=100||b.ts!==64&&b.ts!==96&&b.ts!==128||b.ks!==128&&b.ks!==192&&b.ks!==256||!b.iv||b.iv.length<2||b.iv.length>4)throw new sjcl.exception.invalid("json decrypt: invalid parameters");
typeof a==="string"?(f=sjcl.misc.cachedPbkdf2(a,b),a=f.key.slice(0,b.ks/32),b.salt=f.salt):sjcl.ecc&&a instanceof sjcl.ecc.elGamal.secretKey&&(a=a.unkem(sjcl.codec.base64.toBits(b.kemtag)).slice(0,b.ks/32));typeof c==="string"&&(c=sjcl.codec.utf8String.toBits(c));f=new sjcl.cipher[b.cipher](a);c=sjcl.mode[b.mode].decrypt(f,b.ct,b.iv,c,b.ts);e._add(d,b);d.key=a;return sjcl.codec.utf8String.fromBits(c)},encode:function(a){var b,c="{",d="";for(b in a)if(a.hasOwnProperty(b)){if(!b.match(/^[a-z0-9]+$/i))throw new sjcl.exception.invalid("json encode: invalid property name");
c+=d+'"'+b+'":';d=",";switch(typeof a[b]){case "number":case "boolean":c+=a[b];break;case "string":c+='"'+escape(a[b])+'"';break;case "object":c+='"'+sjcl.codec.base64.fromBits(a[b],0)+'"';break;default:throw new sjcl.exception.bug("json encode: unsupported type");}}return c+"}"},decode:function(a){a=a.replace(/\s/g,"");if(!a.match(/^\{.*\}$/))throw new sjcl.exception.invalid("json decode: this isn't json!");var a=a.replace(/^\{|\}$/g,"").split(/,/),b={},c,d;for(c=0;c<a.length;c++){if(!(d=a[c].match(/^(?:(["']?)([a-z][a-z0-9]*)\1):(?:(\d+)|"([a-z0-9+\/%*_.@=\-]*)")$/i)))throw new sjcl.exception.invalid("json decode: this isn't json!");
b[d[2]]=d[3]?parseInt(d[3],10):d[2].match(/^(ct|salt|iv)$/)?sjcl.codec.base64.toBits(d[4]):unescape(d[4])}return b},_add:function(a,b,c){a===void 0&&(a={});if(b===void 0)return a;for(var d in b)if(b.hasOwnProperty(d)){if(c&&a[d]!==void 0&&a[d]!==b[d])throw new sjcl.exception.invalid("required parameter overridden");a[d]=b[d]}return a},_subtract:function(a,b){var c={},d;for(d in a)a.hasOwnProperty(d)&&a[d]!==b[d]&&(c[d]=a[d]);return c},_filter:function(a,b){var c={},d;for(d=0;d<b.length;d++)a[b[d]]!==
void 0&&(c[b[d]]=a[b[d]]);return c}};sjcl.encrypt=sjcl.json.encrypt;sjcl.decrypt=sjcl.json.decrypt;sjcl.misc._pbkdf2Cache={};sjcl.misc.cachedPbkdf2=function(a,b){var f;var e;var c=sjcl.misc._pbkdf2Cache,d,b=b||{};d=b.iter||1E3;e=c[a]=c[a]||{},c=e;f=c[d]=c[d]||{firstSalt:b.salt&&b.salt.length?b.salt.slice(0):sjcl.random.randomWords(2,0)},d=f;c=b.salt===void 0?d.firstSalt:b.salt;d[c]=d[c]||sjcl.misc.pbkdf2(a,c,b.iter);return{key:d[c].slice(0),salt:c.slice(0)}};sjcl.bn=function(a){this.initWith(a)};
sjcl.bn.prototype={radix:24,maxMul:8,_class:sjcl.bn,copy:function(){return new this._class(this)},initWith:function(a){var b=0,c;switch(typeof a){case "object":this.limbs=a.limbs.slice(0);break;case "number":this.limbs=[a];this.normalize();break;case "string":a=a.replace(/^0x/,"");this.limbs=[];c=this.radix/4;for(b=0;b<a.length;b+=c)this.limbs.push(parseInt(a.substring(Math.max(a.length-b-c,0),a.length-b),16));break;default:this.limbs=[0]}return this},equals:function(a){typeof a==="number"&&(a=new this._class(a));
var b=0,c;this.fullReduce();a.fullReduce();for(c=0;c<this.limbs.length||c<a.limbs.length;c++)b|=this.getLimb(c)^a.getLimb(c);return b===0},getLimb:function(a){return a>=this.limbs.length?0:this.limbs[a]},greaterEquals:function(a){typeof a==="number"&&(a=new this._class(a));var b=0,c=0,d,e,f;for(d=Math.max(this.limbs.length,a.limbs.length)-1;d>=0;d--)e=this.getLimb(d),f=a.getLimb(d),c|=f-e&~b,b|=e-f&~c;return(c|~b)>>>31},toString:function(){this.fullReduce();var a="",b,c,d=this.limbs;for(b=0;b<this.limbs.length;b++){for(c=
d[b].toString(16);b<this.limbs.length-1&&c.length<6;)c="0"+c;a=c+a}return"0x"+a},addM:function(a){typeof a!=="object"&&(a=new this._class(a));for(var b=this.limbs,c=a.limbs,a=b.length;a<c.length;a++)b[a]=0;for(a=0;a<c.length;a++)b[a]+=c[a];return this},doubleM:function(){var a,b=0,c,d=this.radix,e=this.radixMask,f=this.limbs;for(a=0;a<f.length;a++)c=f[a],c=c+c+b,f[a]=c&e,b=c>>d;b&&f.push(b);return this},halveM:function(){var a,b=0,c,d=this.radix,e=this.limbs;for(a=e.length-1;a>=0;a--)c=e[a],e[a]=
c+b>>1,b=(c&1)<<d;e[e.length-1]||e.pop();return this},subM:function(a){typeof a!=="object"&&(a=new this._class(a));for(var b=this.limbs,c=a.limbs,a=b.length;a<c.length;a++)b[a]=0;for(a=0;a<c.length;a++)b[a]-=c[a];return this},mod:function(a){var b=!this.greaterEquals(new sjcl.bn(0)),a=(new sjcl.bn(a)).normalize(),c=(new sjcl.bn(this)).normalize(),d=0;for(b&&(c=(new sjcl.bn(0)).subM(c).normalize());c.greaterEquals(a);d++)a.doubleM();for(b&&(c=a.sub(c).normalize());d>0;d--)a.halveM(),c.greaterEquals(a)&&
c.subM(a).normalize();return c.trim()},inverseMod:function(a){var b=new sjcl.bn(1),c=new sjcl.bn(0),d=new sjcl.bn(this),e=new sjcl.bn(a),f,g=1;if(!(a.limbs[0]&1))throw new sjcl.exception.invalid("inverseMod: p must be odd");do{d.limbs[0]&1&&(d.greaterEquals(e)||(f=d,d=e,e=f,f=b,b=c,c=f),d.subM(e),d.normalize(),b.greaterEquals(c)||b.addM(a),b.subM(c));d.halveM();b.limbs[0]&1&&b.addM(a);b.normalize();b.halveM();for(f=g=0;f<d.limbs.length;f++)g|=d.limbs[f]}while(g);if(!e.equals(1))throw new sjcl.exception.invalid("inverseMod: p and x must be relatively prime");
return c},add:function(a){return this.copy().addM(a)},sub:function(a){return this.copy().subM(a)},mul:function(a){typeof a==="number"&&(a=new this._class(a));var b,c=this.limbs,d=a.limbs,e=c.length,f=d.length,g=new this._class,h=g.limbs,i,k=this.maxMul;for(b=0;b<this.limbs.length+a.limbs.length+1;b++)h[b]=0;for(b=0;b<e;b++){i=c[b];for(a=0;a<f;a++)h[b+a]+=i*d[a];if(!--k)k=this.maxMul,g.cnormalize()}return g.cnormalize().reduce()},square:function(){return this.mul(this)},power:function(a){if(typeof a===
"number")a=[a];else if(a.limbs!==void 0)a=a.normalize().limbs;var b,c,d=new this._class(1),e=this;for(b=0;b<a.length;b++)for(c=0;c<this.radix;c++)a[b]&1<<c&&(d=d.mul(e)),e=e.square();return d},mulmod:function(a,b){return this.mod(b).mul(a.mod(b)).mod(b)},powermod:function(a,b){for(var c=new sjcl.bn(1),d=new sjcl.bn(this),e=new sjcl.bn(a);;){e.limbs[0]&1&&(c=c.mulmod(d,b));e.halveM();if(e.equals(0))break;d=d.mulmod(d,b)}return c.normalize().reduce()},trim:function(){var a=this.limbs,b;do b=a.pop();
while(a.length&&b===0);a.push(b);return this},reduce:function(){return this},fullReduce:function(){return this.normalize()},normalize:function(){var a=0,b,c=this.ipv,d,e=this.limbs,f=e.length,g=this.radixMask;for(b=0;b<f||a!==0&&a!==-1;b++)a=(e[b]||0)+a,d=e[b]=a&g,a=(a-d)*c;a===-1&&(e[b-1]-=this.placeVal);return this},cnormalize:function(){var a=0,b,c=this.ipv,d,e=this.limbs,f=e.length,g=this.radixMask;for(b=0;b<f-1;b++)a=e[b]+a,d=e[b]=a&g,a=(a-d)*c;e[b]+=a;return this},toBits:function(a){this.fullReduce();
var a=a||this.exponent||this.bitLength(),b=Math.floor((a-1)/24),c=sjcl.bitArray,d=[c.partial((a+7&-8)%this.radix||this.radix,this.getLimb(b))];for(b--;b>=0;b--)d=c.concat(d,[c.partial(Math.min(this.radix,a),this.getLimb(b))]),a-=this.radix;return d},bitLength:function(){this.fullReduce();for(var a=this.radix*(this.limbs.length-1),b=this.limbs[this.limbs.length-1];b;b>>>=1)a++;return a+7&-8}};
sjcl.bn.fromBits=function(a){var b=new this,c=[],d=sjcl.bitArray,e=this.prototype,f=Math.min(this.bitLength||4294967296,d.bitLength(a)),g=f%e.radix||e.radix;for(c[0]=d.extract(a,0,g);g<f;g+=e.radix)c.unshift(d.extract(a,g,e.radix));b.limbs=c;return b};sjcl.bn.prototype.ipv=1/(sjcl.bn.prototype.placeVal=Math.pow(2,sjcl.bn.prototype.radix));sjcl.bn.prototype.radixMask=(1<<sjcl.bn.prototype.radix)-1;
sjcl.bn.pseudoMersennePrime=function(a,b){function c(a){this.initWith(a)}var d=c.prototype=new sjcl.bn,e,f;e=d.modOffset=Math.ceil(f=a/d.radix);d.exponent=a;d.offset=[];d.factor=[];d.minOffset=e;d.fullMask=0;d.fullOffset=[];d.fullFactor=[];d.modulus=c.modulus=new sjcl.bn(Math.pow(2,a));d.fullMask=0|-Math.pow(2,a%d.radix);for(e=0;e<b.length;e++)d.offset[e]=Math.floor(b[e][0]/d.radix-f),d.fullOffset[e]=Math.ceil(b[e][0]/d.radix-f),d.factor[e]=b[e][1]*Math.pow(0.5,a-b[e][0]+d.offset[e]*d.radix),d.fullFactor[e]=
b[e][1]*Math.pow(0.5,a-b[e][0]+d.fullOffset[e]*d.radix),d.modulus.addM(new sjcl.bn(Math.pow(2,b[e][0])*b[e][1])),d.minOffset=Math.min(d.minOffset,-d.offset[e]);d._class=c;d.modulus.cnormalize();d.reduce=function(){var a,b,c,d=this.modOffset,e=this.limbs,f=this.offset,q=this.offset.length,t=this.factor,z;for(a=this.minOffset;e.length>d;){c=e.pop();z=e.length;for(b=0;b<q;b++)e[z+f[b]]-=t[b]*c;a--;if(!a)e.push(0),this.cnormalize(),a=this.minOffset}this.cnormalize();return this};d._strongReduce=d.fullMask===
-1?d.reduce:function(){var a=this.limbs,b=a.length-1,c,d;this.reduce();if(b===this.modOffset-1){d=a[b]&this.fullMask;a[b]-=d;for(c=0;c<this.fullOffset.length;c++)a[b+this.fullOffset[c]]-=this.fullFactor[c]*d;this.normalize()}};d.fullReduce=function(){var a,b;this._strongReduce();this.addM(this.modulus);this.addM(this.modulus);this.normalize();this._strongReduce();for(b=this.limbs.length;b<this.modOffset;b++)this.limbs[b]=0;a=this.greaterEquals(this.modulus);for(b=0;b<this.limbs.length;b++)this.limbs[b]-=
this.modulus.limbs[b]*a;this.cnormalize();return this};d.inverse=function(){return this.power(this.modulus.sub(2))};c.fromBits=sjcl.bn.fromBits;return c};
sjcl.bn.prime={p127:sjcl.bn.pseudoMersennePrime(127,[[0,-1]]),p25519:sjcl.bn.pseudoMersennePrime(255,[[0,-19]]),p192:sjcl.bn.pseudoMersennePrime(192,[[0,-1],[64,-1]]),p224:sjcl.bn.pseudoMersennePrime(224,[[0,1],[96,-1]]),p256:sjcl.bn.pseudoMersennePrime(256,[[0,-1],[96,1],[192,1],[224,-1]]),p384:sjcl.bn.pseudoMersennePrime(384,[[0,-1],[32,1],[96,-1],[128,-1]]),p521:sjcl.bn.pseudoMersennePrime(521,[[0,-1]])};
sjcl.bn.random=function(a,b){typeof a!=="object"&&(a=new sjcl.bn(a));for(var c,d,e=a.limbs.length,f=a.limbs[e-1]+1,g=new sjcl.bn;;){do c=sjcl.random.randomWords(e,b),c[e-1]<0&&(c[e-1]+=4294967296);while(Math.floor(c[e-1]/f)===Math.floor(4294967296/f));c[e-1]%=f;for(d=0;d<e-1;d++)c[d]&=a.radixMask;g.limbs=c;if(!g.greaterEquals(a))return g}};sjcl.ecc={};
sjcl.ecc.point=function(a,b,c){b===void 0?this.isIdentity=!0:(b instanceof sjcl.bn&&(b=new a.field(b)),c instanceof sjcl.bn&&(c=new a.field(c)),this.x=b,this.y=c,this.isIdentity=!1);this.curve=a};
sjcl.ecc.point.prototype={toJac:function(){return new sjcl.ecc.pointJac(this.curve,this.x,this.y,new this.curve.field(1))},mult:function(a){return this.toJac().mult(a,this).toAffine()},mult2:function(a,b,c){return this.toJac().mult2(a,this,b,c).toAffine()},multiples:function(){var a,b,c;if(this._multiples===void 0){c=this.toJac().doubl();a=this._multiples=[new sjcl.ecc.point(this.curve),this,c.toAffine()];for(b=3;b<16;b++)c=c.add(this),a.push(c.toAffine())}return this._multiples},isValid:function(){return this.y.square().equals(this.curve.b.add(this.x.mul(this.curve.a.add(this.x.square()))))},
toBits:function(){return sjcl.bitArray.concat(this.x.toBits(),this.y.toBits())}};sjcl.ecc.pointJac=function(a,b,c,d){b===void 0?this.isIdentity=!0:(this.x=b,this.y=c,this.z=d,this.isIdentity=!1);this.curve=a};
sjcl.ecc.pointJac.prototype={add:function(a){var b,c,d,e;if(this.curve!==a.curve)throw"sjcl.ecc.add(): Points must be on the same curve to add them!";if(this.isIdentity)return a.toJac();else if(a.isIdentity)return this;b=this.z.square();c=a.x.mul(b).subM(this.x);if(c.equals(0))return this.y.equals(a.y.mul(b.mul(this.z)))?this.doubl():new sjcl.ecc.pointJac(this.curve);b=a.y.mul(b.mul(this.z)).subM(this.y);d=c.square();a=b.square();e=c.square().mul(c).addM(this.x.add(this.x).mul(d));a=a.subM(e);b=this.x.mul(d).subM(a).mul(b);
d=this.y.mul(c.square().mul(c));b=b.subM(d);c=this.z.mul(c);return new sjcl.ecc.pointJac(this.curve,a,b,c)},doubl:function(){if(this.isIdentity)return this;var a=this.y.square(),b=a.mul(this.x.mul(4)),c=a.square().mul(8),a=this.z.square(),d=this.x.sub(a).mul(3).mul(this.x.add(a)),a=d.square().subM(b).subM(b),b=b.sub(a).mul(d).subM(c),c=this.y.add(this.y).mul(this.z);return new sjcl.ecc.pointJac(this.curve,a,b,c)},toAffine:function(){if(this.isIdentity||this.z.equals(0))return new sjcl.ecc.point(this.curve);
var a=this.z.inverse(),b=a.square();return new sjcl.ecc.point(this.curve,this.x.mul(b).fullReduce(),this.y.mul(b.mul(a)).fullReduce())},mult:function(a,b){if(typeof a==="number")a=[a];else if(a.limbs!==void 0)a=a.normalize().limbs;var c,d,e=(new sjcl.ecc.point(this.curve)).toJac(),f=b.multiples();for(c=a.length-1;c>=0;c--)for(d=sjcl.bn.prototype.radix-4;d>=0;d-=4)e=e.doubl().doubl().doubl().doubl().add(f[a[c]>>d&15]);return e},mult2:function(a,b,c,d){if(typeof a==="number")a=[a];else if(a.limbs!==
void 0)a=a.normalize().limbs;if(typeof c==="number")c=[c];else if(c.limbs!==void 0)c=c.normalize().limbs;for(var e,f=(new sjcl.ecc.point(this.curve)).toJac(),b=b.multiples(),g=d.multiples(),h,i,d=Math.max(a.length,c.length)-1;d>=0;d--){h=a[d]|0;i=c[d]|0;for(e=sjcl.bn.prototype.radix-4;e>=0;e-=4)f=f.doubl().doubl().doubl().doubl().add(b[h>>e&15]).add(g[i>>e&15])}return f},isValid:function(){var a=this.z.square(),b=a.square(),a=b.mul(a);return this.y.square().equals(this.curve.b.mul(a).add(this.x.mul(this.curve.a.mul(b).add(this.x.square()))))}};
sjcl.ecc.curve=function(a,b,c,d,e,f){this.field=a;this.r=a.prototype.modulus.sub(b);this.a=new a(c);this.b=new a(d);this.G=new sjcl.ecc.point(this,new a(e),new a(f))};sjcl.ecc.curve.prototype.fromBits=function(a){var b=sjcl.bitArray,c=this.field.prototype.exponent+7&-8,a=new sjcl.ecc.point(this,this.field.fromBits(b.bitSlice(a,0,c)),this.field.fromBits(b.bitSlice(a,c,2*c)));if(!a.isValid())throw new sjcl.exception.corrupt("not on the curve!");return a};
sjcl.ecc.curves={c192:new sjcl.ecc.curve(sjcl.bn.prime.p192,"0x662107c8eb94364e4b2dd7ce",-3,"0x64210519e59c80e70fa7e9ab72243049feb8deecc146b9b1","0x188da80eb03090f67cbf20eb43a18800f4ff0afd82ff1012","0x07192b95ffc8da78631011ed6b24cdd573f977a11e794811"),c224:new sjcl.ecc.curve(sjcl.bn.prime.p224,"0xe95c1f470fc1ec22d6baa3a3d5c4",-3,"0xb4050a850c04b3abf54132565044b0b7d7bfd8ba270b39432355ffb4","0xb70e0cbd6bb4bf7f321390b94a03c1d356c21122343280d6115c1d21","0xbd376388b5f723fb4c22dfe6cd4375a05a07476444d5819985007e34"),
c256:new sjcl.ecc.curve(sjcl.bn.prime.p256,"0x4319055358e8617b0c46353d039cdaae",-3,"0x5ac635d8aa3a93e7b3ebbd55769886bc651d06b0cc53b0f63bce3c3e27d2604b","0x6b17d1f2e12c4247f8bce6e563a440f277037d812deb33a0f4a13945d898c296","0x4fe342e2fe1a7f9b8ee7eb4a7c0f9e162bce33576b315ececbb6406837bf51f5"),c384:new sjcl.ecc.curve(sjcl.bn.prime.p384,"0x389cb27e0bc8d21fa7e5f24cb74f58851313e696333ad68c",-3,"0xb3312fa7e23ee7e4988e056be3f82d19181d9c6efe8141120314088f5013875ac656398d8a2ed19d2a85c8edd3ec2aef","0xaa87ca22be8b05378eb1c71ef320ad746e1d3b628ba79b9859f741e082542a385502f25dbf55296c3a545e3872760ab7",
"0x3617de4a96262c6f5d9e98bf9292dc29f8f41dbd289a147ce9da3113b5f0b8c00a60b1ce1d7e819d7a431d7c90ea0e5f")};
sjcl.ecc._dh=function(a){sjcl.ecc[a]={publicKey:function(a,c){this._curve=a;this._curveBitLength=a.r.bitLength();this._point=c instanceof Array?a.fromBits(c):c;this.get=function(){var a=this._point.toBits(),b=sjcl.bitArray.bitLength(a),c=sjcl.bitArray.bitSlice(a,0,b/2),a=sjcl.bitArray.bitSlice(a,b/2);return{x:c,y:a}}},secretKey:function(a,c){this._curve=a;this._curveBitLength=a.r.bitLength();this._exponent=c;this.get=function(){return this._exponent.toBits()}},generateKeys:function(b,c,d){b===void 0&&
(b=256);if(typeof b==="number"&&(b=sjcl.ecc.curves["c"+b],b===void 0))throw new sjcl.exception.invalid("no such curve");d===void 0&&(d=sjcl.bn.random(b.r,c));c=b.G.mult(d);return{pub:new sjcl.ecc[a].publicKey(b,c),sec:new sjcl.ecc[a].secretKey(b,d)}}}};sjcl.ecc._dh("elGamal");sjcl.ecc.elGamal.publicKey.prototype={kem:function(a){var a=sjcl.bn.random(this._curve.r,a),b=this._curve.G.mult(a).toBits();return{key:sjcl.hash.sha256.hash(this._point.mult(a).toBits()),tag:b}}};
sjcl.ecc.elGamal.secretKey.prototype={unkem:function(a){return sjcl.hash.sha256.hash(this._curve.fromBits(a).mult(this._exponent).toBits())},dh:function(a){return sjcl.hash.sha256.hash(a._point.mult(this._exponent).toBits())}};sjcl.ecc._dh("ecdsa");
sjcl.ecc.ecdsa.secretKey.prototype={sign:function(a,b,c,d){sjcl.bitArray.bitLength(a)>this._curveBitLength&&(a=sjcl.bitArray.clamp(a,this._curveBitLength));var e=this._curve.r,f=e.bitLength(),d=d||sjcl.bn.random(e.sub(1),b).add(1),b=this._curve.G.mult(d).x.mod(e),a=sjcl.bn.fromBits(a).add(b.mul(this._exponent)),c=c?a.inverseMod(e).mul(d).mod(e):a.mul(d.inverseMod(e)).mod(e);return sjcl.bitArray.concat(b.toBits(f),c.toBits(f))}};
sjcl.ecc.ecdsa.publicKey.prototype={verify:function(a,b,c){sjcl.bitArray.bitLength(a)>this._curveBitLength&&(a=sjcl.bitArray.clamp(a,this._curveBitLength));var d=sjcl.bitArray,e=this._curve.r,f=this._curveBitLength,g=sjcl.bn.fromBits(d.bitSlice(b,0,f)),d=sjcl.bn.fromBits(d.bitSlice(b,f,2*f)),h=c?d:d.inverseMod(e),f=sjcl.bn.fromBits(a).mul(h).mod(e),h=g.mul(h).mod(e),f=this._curve.G.mult2(f,h,this._point).x;if(g.equals(0)||d.equals(0)||g.greaterEquals(e)||d.greaterEquals(e)||!f.equals(g))if(c===void 0)return this.verify(a,
b,!0);else throw new sjcl.exception.corrupt("signature didn't check out");return!0}};sjcl.ecc.point.prototype.isValidPoint=function(){var a=this.curve.field.modulus;return this.isIdentity?!1:(new sjcl.bn(1)).greaterEquals(this.x)&&!this.x.equals(1)||this.x.greaterEquals(a.sub(1))&&!this.x.equals(1)?!1:(new sjcl.bn(1)).greaterEquals(this.y)&&!this.y.equals(1)||this.y.greaterEquals(a.sub(1))&&!this.y.equals(1)?!1:!this.isOnCurve()?!1:!0};
sjcl.ecc.point.prototype.isOnCurve=function(){var a=this.curve.a,b=this.curve.b,c=this.curve.field.modulus,d=this.y.mul(this.y).mod(c),a=this.x.mul(this.x).mul(this.x).add(a.mul(this.x)).add(b).mod(c);return d.equals(a)};sjcl.ecc.point.prototype.toString=function(){return"("+this.x.toString()+", "+this.y.toString()+")"};sjcl.ecc.pointJac.prototype.toString=function(){return"("+this.x.toString()+", "+this.y.toString()+", "+this.z.toString()+")"};
sjcl.ecc.curves.c256=new sjcl.ecc.curve(sjcl.bn.pseudoMersennePrime(256,[[0,-1],[4,-1],[6,-1],[7,-1],[8,-1],[9,-1],[32,-1]]),"0x14551231950b75fc4402da1722fc9baee",0,7,"0x79be667ef9dcbbac55a06295ce870b07029bfcdb2dce28d959f2815b16f81798","0x483ada7726a3c4655da4fbfc0e1108a8fd17b448a68554199c47d08ffb10d4b8");
sjcl.ecc.pointJac.prototype.add=function(a){if(this.curve!==a.curve)throw"sjcl.ecc.add(): Points must be on the same curve to add them!";if(this.isIdentity)return a.toJac();else if(a.isIdentity)return this;var b=this.z.square(),c=a.x.mul(b).subM(this.x),d=a.y.mul(this.z).mul(b);if(c.equals(0))return this.y.equals(a.y.mul(b.mul(this.z)))?this.doubl():new sjcl.ecc.pointJac(this.curve);var a=c.square(),e=a.copy().doubleM().doubleM(),f=c.mul(e),g=d.sub(this.y).doubleM(),e=this.x.mul(e),d=g.square().subM(f).subM(e.copy().doubleM()),
f=g.mul(e.sub(d)).subM(this.y.mul(f).doubleM()),b=this.z.add(c).square().subM(b).subM(a);return new sjcl.ecc.pointJac(this.curve,d,f,b)};sjcl.ecc.pointJac.prototype.doubl=function(){if(this.isIdentity)return this;var a=this.x.square(),b=this.y.square(),c=b.square(),b=this.x.add(b).square().subM(a).subM(c).doubleM(),d=a.mul(3),a=d.square().sub(b.copy().doubleM()),c=d.mul(b.sub(a)).subM(c.doubleM().doubleM().doubleM()),b=this.z.mul(this.y).doubleM();return new sjcl.ecc.pointJac(this.curve,a,c,b)};
sjcl.ecc.point.prototype.toBytesCompressed=function(){return[this.y.mod(2).toString()=="0x0"?2:3].concat(sjcl.codec.bytes.fromBits(this.x.toBits()))};
(function(){function a(a,b){return a<<b|a>>>32-b}function b(a){return(a&255)<<24|(a&65280)<<8|(a&16711680)>>>8|(a&-16777216)>>>24}function c(b){for(var c=this._h[0],d=this._h[1],g=this._h[2],h=this._h[3],p=this._h[4],u=this._h[0],r=this._h[1],v=this._h[2],s=this._h[3],n=this._h[4],j=0,o;j<16;++j)o=a(c+(d^g^h)+b[i[j]]+e[j],l[j])+p,c=p,p=h,h=a(g,10),g=d,d=o,o=a(u+(r^(v|~s))+b[k[j]]+f[j],m[j])+n,u=n,n=s,s=a(v,10),v=r,r=o;for(;j<32;++j)o=a(c+(d&g|~d&h)+b[i[j]]+e[j],l[j])+p,c=p,p=h,h=a(g,10),g=d,d=o,o=
a(u+(r&s|v&~s)+b[k[j]]+f[j],m[j])+n,u=n,n=s,s=a(v,10),v=r,r=o;for(;j<48;++j)o=a(c+((d|~g)^h)+b[i[j]]+e[j],l[j])+p,c=p,p=h,h=a(g,10),g=d,d=o,o=a(u+((r|~v)^s)+b[k[j]]+f[j],m[j])+n,u=n,n=s,s=a(v,10),v=r,r=o;for(;j<64;++j)o=a(c+(d&h|g&~h)+b[i[j]]+e[j],l[j])+p,c=p,p=h,h=a(g,10),g=d,d=o,o=a(u+(r&v|~r&s)+b[k[j]]+f[j],m[j])+n,u=n,n=s,s=a(v,10),v=r,r=o;for(;j<80;++j)o=a(c+(d^(g|~h))+b[i[j]]+e[j],l[j])+p,c=p,p=h,h=a(g,10),g=d,d=o,o=a(u+(r^v^s)+b[k[j]]+f[j],m[j])+n,u=n,n=s,s=a(v,10),v=r,r=o;o=this._h[1]+g+s;
this._h[1]=this._h[2]+h+n;this._h[2]=this._h[3]+p+u;this._h[3]=this._h[4]+c+r;this._h[4]=this._h[0]+d+v;this._h[0]=o}sjcl.hash.ripemd160=function(a){a?(this._h=a._h.slice(0),this._buffer=a._buffer.slice(0),this._length=a._length):this.reset()};sjcl.hash.ripemd160.hash=function(a){return(new sjcl.hash.ripemd160).update(a).finalize()};sjcl.hash.ripemd160.prototype={reset:function(){this._h=d.slice(0);this._buffer=[];this._length=0;return this},update:function(a){typeof a==="string"&&(a=sjcl.codec.utf8String.toBits(a));
var d,e=this._buffer=sjcl.bitArray.concat(this._buffer,a);d=this._length;a=this._length=d+sjcl.bitArray.bitLength(a);for(d=512+d&-512;d<=a;d+=512){for(var f=e.splice(0,16),g=0;g<16;++g)f[g]=b(f[g]);c.call(this,f)}return this},finalize:function(){var a=sjcl.bitArray.concat(this._buffer,[sjcl.bitArray.partial(1,1)]),d=(this._length+1)%512,d=(d>448?512:448)-d%448,e=d%32;for(e>0&&(a=sjcl.bitArray.concat(a,[sjcl.bitArray.partial(e,0)]));d>=32;d-=32)a.push(0);a.push(b(this._length|0));for(a.push(b(Math.floor(this._length/
4294967296)));a.length;){e=a.splice(0,16);for(d=0;d<16;++d)e[d]=b(e[d]);c.call(this,e)}a=this._h;this.reset();for(d=0;d<5;++d)a[d]=b(a[d]);return a}};for(var d=[1732584193,4023233417,2562383102,271733878,3285377520],e=[0,1518500249,1859775393,2400959708,2840853838],f=[1352829926,1548603684,1836072691,2053994217,0],g=4;g>=0;--g)for(var h=1;h<16;++h)e.splice(g,0,e[g]),f.splice(g,0,f[g]);var i=[0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,7,4,13,1,10,6,15,3,12,0,9,5,2,14,11,8,3,10,14,4,9,15,8,1,2,7,0,6,13,
11,5,12,1,9,11,10,0,8,12,4,13,3,7,15,14,5,6,2,4,0,5,9,7,12,2,10,14,1,3,8,11,6,15,13],k=[5,14,7,0,9,2,11,4,13,6,15,8,1,10,3,12,6,11,3,7,0,13,5,10,14,15,8,12,4,9,1,2,15,5,1,3,7,14,6,9,11,8,12,2,10,0,4,13,8,6,4,1,3,11,15,0,5,12,2,13,9,7,10,14,12,15,10,4,1,5,8,7,6,2,13,14,0,3,9,11],l=[11,14,15,12,5,8,7,9,11,13,14,15,6,7,9,8,7,6,8,13,11,9,7,15,7,12,15,9,11,7,13,12,11,13,6,7,14,9,13,15,14,8,13,6,5,12,7,5,11,12,14,15,14,15,9,8,9,14,5,6,8,6,5,12,9,15,5,11,6,8,13,12,5,12,13,14,11,8,5,6],m=[8,9,9,11,13,15,
15,5,7,7,8,11,14,14,12,6,9,13,15,7,12,8,9,11,7,7,12,7,6,15,13,11,9,7,15,11,8,6,6,14,12,13,5,14,13,13,7,5,15,5,8,11,14,14,6,14,6,9,12,9,12,5,15,8,8,5,12,9,12,5,14,6,8,13,6,5,15,13,11,11]})();sjcl.bn.ZERO=new sjcl.bn(0);
sjcl.bn.prototype.divRem=function(a){typeof a!=="object"&&(a=new this._class(a));var b=this.abs(),c=a.abs(),d=new this._class(0),e=0;if(b.greaterEquals(c)){if(b.equals(c))return[new sjcl.bn(1),new sjcl.bn(0)]}else return[new sjcl.bn(0),this.copy()];for(;b.greaterEquals(c);e++)c.doubleM();for(;e>0;e--)d.doubleM(),c.halveM(),b.greaterEquals(c)&&(d.addM(1),b.subM(a).normalize());return[d,b]};
sjcl.bn.prototype.divRound=function(a){var b=this.divRem(a),c=b[0];b[1].doubleM().greaterEquals(a)&&c.addM(1);return c};sjcl.bn.prototype.div=function(a){return this.divRem(a)[0]};sjcl.bn.prototype.sign=function(){return this.greaterEquals(sjcl.bn.ZERO)?1:-1};sjcl.bn.prototype.neg=function(){return sjcl.bn.ZERO.sub(this)};sjcl.bn.prototype.abs=function(){return this.sign()===-1?this.neg():this};
sjcl.bn.prototype.shiftRight=function(a){if("number"!==typeof a)throw Error("shiftRight expects a number");a=+a;if(a<0)return this.shiftLeft(a);for(var b=new sjcl.bn(this);a>=this.radix;)b.limbs.shift(),a-=this.radix;for(;a--;)b.halveM();return b};sjcl.bn.prototype.shiftLeft=function(a){if("number"!==typeof a)throw Error("shiftLeft expects a number");a=+a;if(a<0)return this.shiftRight(a);for(var b=new sjcl.bn(this);a>=this.radix;)b.limbs.unshift(0),a-=this.radix;for(;a--;)b.doubleM();return b};
sjcl.bn.prototype.toNumber=function(){return this.limbs[0]|0};sjcl.bn.prototype.testBit=function(a){var b=Math.floor(a/this.radix);a%=this.radix;return b>=this.limbs.length?0:this.limbs[b]>>>a&1};sjcl.bn.prototype.setBitM=function(a){var b=Math.floor(a/this.radix);for(a%=this.radix;b>=this.limbs.length;)this.limbs.push(0);this.limbs[b]|=1<<a;this.cnormalize();return this};sjcl.bn.prototype.modInt=function(a){return this.toNumber()%a};
sjcl.bn.prototype.invDigit=function(){var a=1+this.radixMask;if(this.limbs.length<1)return 0;var b=this.limbs[0];if((b&1)==0)return 0;var c=b&3,c=c*(2-(b&15)*c)&15,c=c*(2-(b&255)*c)&255,c=c*(2-((b&65535)*c&65535))&65535,c=c*(2-b*c%a)%a;return c>0?a-c:-c};function nbits(a){var b=1,c;if((c=a>>>16)!=0)a=c,b+=16;if((c=a>>8)!=0)a=c,b+=8;if((c=a>>4)!=0)a=c,b+=4;if((c=a>>2)!=0)a=c,b+=2;a>>1!=0&&(b+=1);return b}
sjcl.bn.prototype.am=function(a,b,c,d,e,f){var g=b&4095;for(b>>=12;--f>=0;){var h=this.limbs[a]&4095,i=this.limbs[a++]>>12,k=b*h+i*g,h=g*h+((k&4095)<<12)+c.limbs[d]+e,e=(h>>24)+(k>>12)+b*i;c.limbs[d++]=h&16777215}return e};var Montgomery=function(a){this.m=a;this.mt=a.limbs.length;this.mt2=this.mt*2;this.mp=a.invDigit();this.mpl=this.mp&32767;this.mph=this.mp>>15;this.um=(1<<a.radix-15)-1};
Montgomery.prototype.reduce=function(a){for(var b=a.radixMask+1;a.limbs.length<=this.mt2;)a.limbs[a.limbs.length]=0;for(var c=0;c<this.mt;++c){var d=a.limbs[c]&32767,e=d*this.mpl+((d*this.mph+(a.limbs[c]>>15)*this.mpl&this.um)<<15)&a.radixMask,d=c+this.mt;for(a.limbs[d]+=this.m.am(0,e,a,c,0,this.mt);a.limbs[d]>=b;)a.limbs[d]-=b,a.limbs[++d]++}a.trim();a=a.shiftRight(this.mt*this.m.radix);a.greaterEquals(this.m)&&(a=a.sub(this.m));return a.trim().normalize().reduce()};Montgomery.prototype.square=function(a){return this.reduce(a.square())};
Montgomery.prototype.multiply=function(a,b){return this.reduce(a.mul(b))};Montgomery.prototype.convert=function(a){return a.abs().shiftLeft(this.mt*this.m.radix).mod(this.m)};Montgomery.prototype.revert=function(a){return this.reduce(a.copy())};
sjcl.bn.prototype.powermodMontgomery=function(a,b){var c=a.bitLength(),d,e=new this._class(1);if(c<=0)return e;else d=c<18?1:c<48?3:c<144?4:c<768?5:6;if(c<8||!b.testBit(0))return this.powermod(a,b);var f=new Montgomery(b);a.trim().normalize();var g=[],h=3,i=d-1,k=(1<<d)-1;g[1]=f.convert(this);if(d>1)for(c=f.square(g[1]);h<=k;)g[h]=f.multiply(c,g[h-2]),h+=2;for(var l=a.limbs.length-1,m,q=!0,t=new this._class,c=nbits(a.limbs[l])-1;l>=0;){c>=i?m=a.limbs[l]>>c-i&k:(m=(a.limbs[l]&(1<<c+1)-1)<<i-c,l>0&&
(m|=a.limbs[l-1]>>this.radix+c-i));for(h=d;(m&1)==0;)m>>=1,--h;if((c-=h)<0)c+=this.radix,--l;if(q)e=g[m].copy(),q=!1;else{for(;h>1;)t=f.square(e),e=f.square(t),h-=2;t=h>0?f.square(e):e;e=f.multiply(t,g[m])}for(;l>=0&&(a.limbs[l]&1<<c)==0;)e=t=f.square(e),--c<0&&(c=this.radix-1,--l)}return f.revert(e)};
sjcl.ecc.ecdsa.secretKey.prototype.sign=function(a,b,c){var d=this._curve.r,e=d.bitLength(),c=typeof c==="object"&&c.length>0&&typeof c[0]==="number"?c:typeof c==="string"&&/^[0-9a-fA-F]+$/.test(c)?sjcl.bn.fromBits(sjcl.codec.hex.toBits(c)):sjcl.bn.random(d.sub(1),b).add(1),b=this._curve.G.mult(c).x.mod(d),a=sjcl.bn.fromBits(a).add(b.mul(this._exponent)).mul(c.inverseMod(d)).mod(d);return sjcl.bitArray.concat(b.toBits(e),a.toBits(e))};var FIELD_MODULUS_PLUS_ONE_DIVIDED_BY_FOUR;
sjcl.bn.prototype.jacobi=function(a){a=new sjcl.bn(a);if(a.sign()!==-1){if(this.equals(0))return 0;if(this.equals(1))return 1;for(var b=0,c=0;!this.testBit(c);)c++;var d=this.shiftRight(c);if((c&1)===0)b=1;else if(c=a.modInt(8),c===1||c===7)b=1;else if(c===3||c===5)b=-1;a.modInt(4)===3&&d.modInt(4)===3&&(b=-b);return d.equals(1)?b:b*a.mod(d).jacobi(d)}};
function fdh(a,b){var c=b<<3;typeof a==="string"&&(a=sjcl.codec.utf8String.toBits(a));for(var d=0,e=[];sjcl.bitArray.bitLength(e)<c;){var f=sjcl.hash.sha512.hash(sjcl.bitArray.concat([d],a)),e=sjcl.bitArray.concat(e,f);d++}return e=sjcl.bitArray.clamp(e,c)}function keyHash(a,b){var c=new sjcl.misc.hmac(a,sjcl.hash.sha512);return sjcl.codec.hex.fromBits(sjcl.bitArray.bitSlice(c.encrypt(b),0,256))}function bn(a){return(new sjcl.bn(String(a))).toString()}
function loadData(a,b,c,d,e,f,g){b=new sjcl.bn(String(b));c=new sjcl.bn(String(c));d=new sjcl.bn(String(d));a="PAKDF_1_0_0:"+a.length+":"+a+":"+f.length+":"+f+":"+e.length+":"+e+":";e=Math.ceil(Math.min(7+c.bitLength()>>>3,256)/8);e=fdh(a,e);e=sjcl.codec.hex.fromBits(e);e=(new sjcl.bn(String(e))).setBitM(0);g=a+":"+g.length+":"+g+":";f=7+c.bitLength()>>>3;g=fdh(g,f);g=sjcl.codec.hex.fromBits(g);g=(new sjcl.bn(String(g))).mod(c);g.jacobi(c)!==1&&(g=g.mul(d).mod(c));for(var h;;)if(h=sjcl.bn.random(c,
0),h.jacobi(c)===1)break;b=h.powermodMontgomery(e.mul(b),c);b=g.mulmod(b,c);b=sjcl.codec.hex.fromBits(b.toBits());return a+","+b+","+h+","+c}function loadData2(a,b,c,d){var b=new sjcl.bn(String(b)),c=new sjcl.bn(String(c)),d=new sjcl.bn(String(d)),c=c.inverseMod(d),e=b.mulmod(c,d).toBits();if(a==="login"){var a=["id","crypt"],f={};a.forEach(function(a){f[a]=keyHash(e,a)});return f.id+","+f.crypt}else return a=["unlock"],f={},a.forEach(function(a){f[a]=keyHash(e,a)}),f.unlock}
function keyHash(a,b){var c=new sjcl.misc.hmac(a,sjcl.hash.sha512);return sjcl.codec.hex.fromBits(sjcl.bitArray.bitSlice(c.encrypt(b),0,256))}
function decrypt(a,b){var a=sjcl.codec.hex.toBits(a),c=sjcl.codec.base64.toBits(b),d=sjcl.bitArray.extract(c,0,8);if(d!==0)throw Error("Unsupported encryption version: "+d);c=extend(!0,{},cryptConfig,{iv:sjcl.codec.base64.fromBits(sjcl.bitArray.bitSlice(c,8,136)),ct:sjcl.codec.base64.fromBits(sjcl.bitArray.bitSlice(c,136))});return sjcl.decrypt(a,JSON.stringify(c))};
